package so.trophy.resources.admin.metrics;

/**
 * This file was auto-generated by Fern from our API Definition.
 */


import so.trophy.core.ClientOptions;
import so.trophy.core.RequestOptions;
import java.lang.String;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import so.trophy.resources.admin.metrics.requests.MetricsDeleteRequest;
import so.trophy.resources.admin.metrics.requests.MetricsListRequest;
import so.trophy.types.CreateMetricRequestItem;
import so.trophy.types.CreateMetricsResponse;
import so.trophy.types.CreatedMetric;
import so.trophy.types.DeleteMetricsResponse;
import so.trophy.types.UpdateMetricRequestItem;
import so.trophy.types.UpdateMetricsResponse;

public class AsyncMetricsClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawMetricsClient rawClient;

  public AsyncMetricsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawMetricsClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawMetricsClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * List metrics.
   */
  public CompletableFuture<List<CreatedMetric>> list() {
    return this.rawClient.list().thenApply(response -> response.body());
  }

  /**
   * List metrics.
   */
  public CompletableFuture<List<CreatedMetric>> list(MetricsListRequest request) {
    return this.rawClient.list(request).thenApply(response -> response.body());
  }

  /**
   * List metrics.
   */
  public CompletableFuture<List<CreatedMetric>> list(MetricsListRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.list(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Create metrics.
   */
  public CompletableFuture<CreateMetricsResponse> create(List<CreateMetricRequestItem> request) {
    return this.rawClient.create(request).thenApply(response -> response.body());
  }

  /**
   * Create metrics.
   */
  public CompletableFuture<CreateMetricsResponse> create(List<CreateMetricRequestItem> request,
      RequestOptions requestOptions) {
    return this.rawClient.create(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Delete metrics by ID.
   */
  public CompletableFuture<DeleteMetricsResponse> delete() {
    return this.rawClient.delete().thenApply(response -> response.body());
  }

  /**
   * Delete metrics by ID.
   */
  public CompletableFuture<DeleteMetricsResponse> delete(MetricsDeleteRequest request) {
    return this.rawClient.delete(request).thenApply(response -> response.body());
  }

  /**
   * Delete metrics by ID.
   */
  public CompletableFuture<DeleteMetricsResponse> delete(MetricsDeleteRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.delete(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Update metrics by ID.
   */
  public CompletableFuture<UpdateMetricsResponse> update(List<UpdateMetricRequestItem> request) {
    return this.rawClient.update(request).thenApply(response -> response.body());
  }

  /**
   * Update metrics by ID.
   */
  public CompletableFuture<UpdateMetricsResponse> update(List<UpdateMetricRequestItem> request,
      RequestOptions requestOptions) {
    return this.rawClient.update(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get a metric by ID.
   */
  public CompletableFuture<CreatedMetric> get(String id) {
    return this.rawClient.get(id).thenApply(response -> response.body());
  }

  /**
   * Get a metric by ID.
   */
  public CompletableFuture<CreatedMetric> get(String id, RequestOptions requestOptions) {
    return this.rawClient.get(id, requestOptions).thenApply(response -> response.body());
  }
}
