/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Double;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = AchievementResponse.Builder.class
)
public final class AchievementResponse {
  private final String id;

  private final Optional<String> name;

  private final Optional<String> badgeUrl;

  private final Optional<String> metricId;

  private final Optional<Double> metricValue;

  private final Optional<String> metricName;

  private final Optional<String> key;

  private final Optional<OffsetDateTime> achievedAt;

  private final Map<String, Object> additionalProperties;

  private AchievementResponse(String id, Optional<String> name, Optional<String> badgeUrl,
      Optional<String> metricId, Optional<Double> metricValue, Optional<String> metricName,
      Optional<String> key, Optional<OffsetDateTime> achievedAt,
      Map<String, Object> additionalProperties) {
    this.id = id;
    this.name = name;
    this.badgeUrl = badgeUrl;
    this.metricId = metricId;
    this.metricValue = metricValue;
    this.metricName = metricName;
    this.key = key;
    this.achievedAt = achievedAt;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The unique ID of the achievement.
   */
  @JsonProperty("id")
  public String getId() {
    return id;
  }

  /**
   * @return The name of this achievement.
   */
  @JsonProperty("name")
  public Optional<String> getName() {
    return name;
  }

  /**
   * @return The URL of the badge image for the achievement, if one has been uploaded.
   */
  @JsonProperty("badgeUrl")
  public Optional<String> getBadgeUrl() {
    return badgeUrl;
  }

  /**
   * @return The ID of the metric associated with this achievement, if any.
   */
  @JsonProperty("metricId")
  public Optional<String> getMetricId() {
    return metricId;
  }

  /**
   * @return The value of the metric required to complete the achievement, if this achievement is associated with a metric.
   */
  @JsonProperty("metricValue")
  public Optional<Double> getMetricValue() {
    return metricValue;
  }

  /**
   * @return The name of the metric associated with this achievement, if any.
   */
  @JsonProperty("metricName")
  public Optional<String> getMetricName() {
    return metricName;
  }

  /**
   * @return The key used to reference this achievement in the API.
   */
  @JsonProperty("key")
  public Optional<String> getKey() {
    return key;
  }

  /**
   * @return The date and time the achievement was completed, in ISO 8601 format.
   */
  @JsonProperty("achievedAt")
  public Optional<OffsetDateTime> getAchievedAt() {
    return achievedAt;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof AchievementResponse && equalTo((AchievementResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(AchievementResponse other) {
    return id.equals(other.id) && name.equals(other.name) && badgeUrl.equals(other.badgeUrl) && metricId.equals(other.metricId) && metricValue.equals(other.metricValue) && metricName.equals(other.metricName) && key.equals(other.key) && achievedAt.equals(other.achievedAt);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.name, this.badgeUrl, this.metricId, this.metricValue, this.metricName, this.key, this.achievedAt);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static IdStage builder() {
    return new Builder();
  }

  public interface IdStage {
    _FinalStage id(@NotNull String id);

    Builder from(AchievementResponse other);
  }

  public interface _FinalStage {
    AchievementResponse build();

    _FinalStage name(Optional<String> name);

    _FinalStage name(String name);

    _FinalStage badgeUrl(Optional<String> badgeUrl);

    _FinalStage badgeUrl(String badgeUrl);

    _FinalStage metricId(Optional<String> metricId);

    _FinalStage metricId(String metricId);

    _FinalStage metricValue(Optional<Double> metricValue);

    _FinalStage metricValue(Double metricValue);

    _FinalStage metricName(Optional<String> metricName);

    _FinalStage metricName(String metricName);

    _FinalStage key(Optional<String> key);

    _FinalStage key(String key);

    _FinalStage achievedAt(Optional<OffsetDateTime> achievedAt);

    _FinalStage achievedAt(OffsetDateTime achievedAt);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements IdStage, _FinalStage {
    private String id;

    private Optional<OffsetDateTime> achievedAt = Optional.empty();

    private Optional<String> key = Optional.empty();

    private Optional<String> metricName = Optional.empty();

    private Optional<Double> metricValue = Optional.empty();

    private Optional<String> metricId = Optional.empty();

    private Optional<String> badgeUrl = Optional.empty();

    private Optional<String> name = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(AchievementResponse other) {
      id(other.getId());
      name(other.getName());
      badgeUrl(other.getBadgeUrl());
      metricId(other.getMetricId());
      metricValue(other.getMetricValue());
      metricName(other.getMetricName());
      key(other.getKey());
      achievedAt(other.getAchievedAt());
      return this;
    }

    /**
     * <p>The unique ID of the achievement.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("id")
    public _FinalStage id(@NotNull String id) {
      this.id = Objects.requireNonNull(id, "id must not be null");
      return this;
    }

    /**
     * <p>The date and time the achievement was completed, in ISO 8601 format.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage achievedAt(OffsetDateTime achievedAt) {
      this.achievedAt = Optional.ofNullable(achievedAt);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "achievedAt",
        nulls = Nulls.SKIP
    )
    public _FinalStage achievedAt(Optional<OffsetDateTime> achievedAt) {
      this.achievedAt = achievedAt;
      return this;
    }

    /**
     * <p>The key used to reference this achievement in the API.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage key(String key) {
      this.key = Optional.ofNullable(key);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "key",
        nulls = Nulls.SKIP
    )
    public _FinalStage key(Optional<String> key) {
      this.key = key;
      return this;
    }

    /**
     * <p>The name of the metric associated with this achievement, if any.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage metricName(String metricName) {
      this.metricName = Optional.ofNullable(metricName);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "metricName",
        nulls = Nulls.SKIP
    )
    public _FinalStage metricName(Optional<String> metricName) {
      this.metricName = metricName;
      return this;
    }

    /**
     * <p>The value of the metric required to complete the achievement, if this achievement is associated with a metric.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage metricValue(Double metricValue) {
      this.metricValue = Optional.ofNullable(metricValue);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "metricValue",
        nulls = Nulls.SKIP
    )
    public _FinalStage metricValue(Optional<Double> metricValue) {
      this.metricValue = metricValue;
      return this;
    }

    /**
     * <p>The ID of the metric associated with this achievement, if any.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage metricId(String metricId) {
      this.metricId = Optional.ofNullable(metricId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "metricId",
        nulls = Nulls.SKIP
    )
    public _FinalStage metricId(Optional<String> metricId) {
      this.metricId = metricId;
      return this;
    }

    /**
     * <p>The URL of the badge image for the achievement, if one has been uploaded.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage badgeUrl(String badgeUrl) {
      this.badgeUrl = Optional.ofNullable(badgeUrl);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "badgeUrl",
        nulls = Nulls.SKIP
    )
    public _FinalStage badgeUrl(Optional<String> badgeUrl) {
      this.badgeUrl = badgeUrl;
      return this;
    }

    /**
     * <p>The name of this achievement.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage name(String name) {
      this.name = Optional.ofNullable(name);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "name",
        nulls = Nulls.SKIP
    )
    public _FinalStage name(Optional<String> name) {
      this.name = name;
      return this;
    }

    @java.lang.Override
    public AchievementResponse build() {
      return new AchievementResponse(id, name, badgeUrl, metricId, metricValue, metricName, key, achievedAt, additionalProperties);
    }
  }
}
