/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = MetricResponse.Builder.class
)
public final class MetricResponse {
  private final String id;

  private final String key;

  private final String name;

  private final String emoji;

  private final StreakFrequency streakFrequency;

  private final MetricStatus status;

  private final double current;

  private final List<AchievementResponse> achievements;

  private final Optional<StreakResponse> streak;

  private final Map<String, Object> additionalProperties;

  private MetricResponse(String id, String key, String name, String emoji,
      StreakFrequency streakFrequency, MetricStatus status, double current,
      List<AchievementResponse> achievements, Optional<StreakResponse> streak,
      Map<String, Object> additionalProperties) {
    this.id = id;
    this.key = key;
    this.name = name;
    this.emoji = emoji;
    this.streakFrequency = streakFrequency;
    this.status = status;
    this.current = current;
    this.achievements = achievements;
    this.streak = streak;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The unique ID of the metric.
   */
  @JsonProperty("id")
  public String getId() {
    return id;
  }

  /**
   * @return The unique key of the metric.
   */
  @JsonProperty("key")
  public String getKey() {
    return key;
  }

  /**
   * @return The name of the metric.
   */
  @JsonProperty("name")
  public String getName() {
    return name;
  }

  /**
   * @return The emoji to represent the metric.
   */
  @JsonProperty("emoji")
  public String getEmoji() {
    return emoji;
  }

  /**
   * @return The frequency of the streak.
   */
  @JsonProperty("streakFrequency")
  public StreakFrequency getStreakFrequency() {
    return streakFrequency;
  }

  /**
   * @return The status of the metric.
   */
  @JsonProperty("status")
  public MetricStatus getStatus() {
    return status;
  }

  /**
   * @return The user's current total for the metric.
   */
  @JsonProperty("current")
  public double getCurrent() {
    return current;
  }

  /**
   * @return A list of the metric's achievements and the user's progress towards each.
   */
  @JsonProperty("achievements")
  public List<AchievementResponse> getAchievements() {
    return achievements;
  }

  /**
   * @return The user's current streak for the metric, if the metric has streaks enabled.
   */
  @JsonProperty("streak")
  public Optional<StreakResponse> getStreak() {
    return streak;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof MetricResponse && equalTo((MetricResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(MetricResponse other) {
    return id.equals(other.id) && key.equals(other.key) && name.equals(other.name) && emoji.equals(other.emoji) && streakFrequency.equals(other.streakFrequency) && status.equals(other.status) && current == other.current && achievements.equals(other.achievements) && streak.equals(other.streak);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.key, this.name, this.emoji, this.streakFrequency, this.status, this.current, this.achievements, this.streak);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static IdStage builder() {
    return new Builder();
  }

  public interface IdStage {
    KeyStage id(@NotNull String id);

    Builder from(MetricResponse other);
  }

  public interface KeyStage {
    NameStage key(@NotNull String key);
  }

  public interface NameStage {
    EmojiStage name(@NotNull String name);
  }

  public interface EmojiStage {
    StreakFrequencyStage emoji(@NotNull String emoji);
  }

  public interface StreakFrequencyStage {
    StatusStage streakFrequency(@NotNull StreakFrequency streakFrequency);
  }

  public interface StatusStage {
    CurrentStage status(@NotNull MetricStatus status);
  }

  public interface CurrentStage {
    _FinalStage current(double current);
  }

  public interface _FinalStage {
    MetricResponse build();

    _FinalStage achievements(List<AchievementResponse> achievements);

    _FinalStage addAchievements(AchievementResponse achievements);

    _FinalStage addAllAchievements(List<AchievementResponse> achievements);

    _FinalStage streak(Optional<StreakResponse> streak);

    _FinalStage streak(StreakResponse streak);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements IdStage, KeyStage, NameStage, EmojiStage, StreakFrequencyStage, StatusStage, CurrentStage, _FinalStage {
    private String id;

    private String key;

    private String name;

    private String emoji;

    private StreakFrequency streakFrequency;

    private MetricStatus status;

    private double current;

    private Optional<StreakResponse> streak = Optional.empty();

    private List<AchievementResponse> achievements = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(MetricResponse other) {
      id(other.getId());
      key(other.getKey());
      name(other.getName());
      emoji(other.getEmoji());
      streakFrequency(other.getStreakFrequency());
      status(other.getStatus());
      current(other.getCurrent());
      achievements(other.getAchievements());
      streak(other.getStreak());
      return this;
    }

    /**
     * <p>The unique ID of the metric.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("id")
    public KeyStage id(@NotNull String id) {
      this.id = Objects.requireNonNull(id, "id must not be null");
      return this;
    }

    /**
     * <p>The unique key of the metric.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("key")
    public NameStage key(@NotNull String key) {
      this.key = Objects.requireNonNull(key, "key must not be null");
      return this;
    }

    /**
     * <p>The name of the metric.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("name")
    public EmojiStage name(@NotNull String name) {
      this.name = Objects.requireNonNull(name, "name must not be null");
      return this;
    }

    /**
     * <p>The emoji to represent the metric.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("emoji")
    public StreakFrequencyStage emoji(@NotNull String emoji) {
      this.emoji = Objects.requireNonNull(emoji, "emoji must not be null");
      return this;
    }

    /**
     * <p>The frequency of the streak.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("streakFrequency")
    public StatusStage streakFrequency(@NotNull StreakFrequency streakFrequency) {
      this.streakFrequency = Objects.requireNonNull(streakFrequency, "streakFrequency must not be null");
      return this;
    }

    /**
     * <p>The status of the metric.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("status")
    public CurrentStage status(@NotNull MetricStatus status) {
      this.status = Objects.requireNonNull(status, "status must not be null");
      return this;
    }

    /**
     * <p>The user's current total for the metric.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("current")
    public _FinalStage current(double current) {
      this.current = current;
      return this;
    }

    /**
     * <p>The user's current streak for the metric, if the metric has streaks enabled.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage streak(StreakResponse streak) {
      this.streak = Optional.ofNullable(streak);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "streak",
        nulls = Nulls.SKIP
    )
    public _FinalStage streak(Optional<StreakResponse> streak) {
      this.streak = streak;
      return this;
    }

    /**
     * <p>A list of the metric's achievements and the user's progress towards each.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addAllAchievements(List<AchievementResponse> achievements) {
      this.achievements.addAll(achievements);
      return this;
    }

    /**
     * <p>A list of the metric's achievements and the user's progress towards each.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addAchievements(AchievementResponse achievements) {
      this.achievements.add(achievements);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "achievements",
        nulls = Nulls.SKIP
    )
    public _FinalStage achievements(List<AchievementResponse> achievements) {
      this.achievements.clear();
      this.achievements.addAll(achievements);
      return this;
    }

    @java.lang.Override
    public MetricResponse build() {
      return new MetricResponse(id, key, name, emoji, streakFrequency, status, current, achievements, streak, additionalProperties);
    }
  }
}
