package so.trophy.src.main.java.resources.admin.streaks.pauses.requests;

/**
 * This file was auto-generated by Fern from our API Definition.
 */


import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import so.trophy.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import so.trophy.resources.admin.streaks.pauses.types.CreateStreakPausesRequestPausesItem;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreateStreakPausesRequest.Builder.class
)
public final class CreateStreakPausesRequest {
  private final List<CreateStreakPausesRequestPausesItem> pauses;

  private final Map<String, Object> additionalProperties;

  private CreateStreakPausesRequest(List<CreateStreakPausesRequestPausesItem> pauses,
      Map<String, Object> additionalProperties) {
    this.pauses = pauses;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Array of pauses to create. Maximum 100 pauses per request.
   */
  @JsonProperty("pauses")
  public List<CreateStreakPausesRequestPausesItem> getPauses() {
    return pauses;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreateStreakPausesRequest && equalTo((CreateStreakPausesRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreateStreakPausesRequest other) {
    return pauses.equals(other.pauses);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.pauses);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private List<CreateStreakPausesRequestPausesItem> pauses = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(CreateStreakPausesRequest other) {
      pauses(other.getPauses());
      return this;
    }

    /**
     * <p>Array of pauses to create. Maximum 100 pauses per request.</p>
     */
    @JsonSetter(
        value = "pauses",
        nulls = Nulls.SKIP
    )
    public Builder pauses(List<CreateStreakPausesRequestPausesItem> pauses) {
      this.pauses.clear();
      if (pauses != null) {
        this.pauses.addAll(pauses);
      }
      return this;
    }

    public Builder addPauses(CreateStreakPausesRequestPausesItem pauses) {
      this.pauses.add(pauses);
      return this;
    }

    public Builder addAllPauses(List<CreateStreakPausesRequestPausesItem> pauses) {
      if (pauses != null) {
        this.pauses.addAll(pauses);
      }
      return this;
    }

    public CreateStreakPausesRequest build() {
      return new CreateStreakPausesRequest(pauses, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
