package so.trophy.src.main.java.resources.admin.achievements;

/**
 * This file was auto-generated by Fern from our API Definition.
 */


import so.trophy.core.ClientOptions;
import so.trophy.core.RequestOptions;
import java.lang.String;
import java.util.List;
import so.trophy.resources.admin.achievements.requests.AchievementsDeleteRequest;
import so.trophy.resources.admin.achievements.requests.AchievementsListRequest;
import so.trophy.types.AdminAchievement;
import so.trophy.types.CreateAchievementRequestItem;
import so.trophy.types.CreateAchievementsResponse;
import so.trophy.types.DeleteAchievementsResponse;
import so.trophy.types.UpdateAchievementRequestItem;
import so.trophy.types.UpdateAchievementsResponse;

public class AchievementsClient {
  protected final ClientOptions clientOptions;

  private final RawAchievementsClient rawClient;

  public AchievementsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new RawAchievementsClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public RawAchievementsClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * List achievements.
   */
  public List<AdminAchievement> list() {
    return this.rawClient.list().body();
  }

  /**
   * List achievements.
   */
  public List<AdminAchievement> list(RequestOptions requestOptions) {
    return this.rawClient.list(requestOptions).body();
  }

  /**
   * List achievements.
   */
  public List<AdminAchievement> list(AchievementsListRequest request) {
    return this.rawClient.list(request).body();
  }

  /**
   * List achievements.
   */
  public List<AdminAchievement> list(AchievementsListRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.list(request, requestOptions).body();
  }

  /**
   * Create achievements. Trigger-specific fields are required based on <code>trigger</code>.
   */
  public CreateAchievementsResponse create(List<CreateAchievementRequestItem> request) {
    return this.rawClient.create(request).body();
  }

  /**
   * Create achievements. Trigger-specific fields are required based on <code>trigger</code>.
   */
  public CreateAchievementsResponse create(List<CreateAchievementRequestItem> request,
      RequestOptions requestOptions) {
    return this.rawClient.create(request, requestOptions).body();
  }

  /**
   * Delete achievements by ID.
   */
  public DeleteAchievementsResponse delete() {
    return this.rawClient.delete().body();
  }

  /**
   * Delete achievements by ID.
   */
  public DeleteAchievementsResponse delete(RequestOptions requestOptions) {
    return this.rawClient.delete(requestOptions).body();
  }

  /**
   * Delete achievements by ID.
   */
  public DeleteAchievementsResponse delete(AchievementsDeleteRequest request) {
    return this.rawClient.delete(request).body();
  }

  /**
   * Delete achievements by ID.
   */
  public DeleteAchievementsResponse delete(AchievementsDeleteRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.delete(request, requestOptions).body();
  }

  /**
   * Update achievements by ID. Maximum 100 achievements per request. Only provided fields are updated; omitted fields are preserved.
   */
  public UpdateAchievementsResponse update(List<UpdateAchievementRequestItem> request) {
    return this.rawClient.update(request).body();
  }

  /**
   * Update achievements by ID. Maximum 100 achievements per request. Only provided fields are updated; omitted fields are preserved.
   */
  public UpdateAchievementsResponse update(List<UpdateAchievementRequestItem> request,
      RequestOptions requestOptions) {
    return this.rawClient.update(request, requestOptions).body();
  }

  /**
   * Get an achievement by ID.
   */
  public AdminAchievement get(String id) {
    return this.rawClient.get(id).body();
  }

  /**
   * Get an achievement by ID.
   */
  public AdminAchievement get(String id, RequestOptions requestOptions) {
    return this.rawClient.get(id, requestOptions).body();
  }
}
