package so.trophy.src.main.java.types;

/**
 * This file was auto-generated by Fern from our API Definition.
 */


import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import so.trophy.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = AdminEnvironment.Builder.class
)
public final class AdminEnvironment {
  private final String name;

  private final String key;

  private final int priority;

  private final Map<String, Object> additionalProperties;

  private AdminEnvironment(String name, String key, int priority,
      Map<String, Object> additionalProperties) {
    this.name = name;
    this.key = key;
    this.priority = priority;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Human-readable name for the environment.
   */
  @JsonProperty("name")
  public String getName() {
    return name;
  }

  /**
   * @return Machine-readable identifier for the environment.
   */
  @JsonProperty("key")
  public String getKey() {
    return key;
  }

  /**
   * @return Environment precedence. Lower numbers take priority. Production is always 1.
   */
  @JsonProperty("priority")
  public int getPriority() {
    return priority;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof AdminEnvironment && equalTo((AdminEnvironment) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(AdminEnvironment other) {
    return name.equals(other.name) && key.equals(other.key) && priority == other.priority;
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.name, this.key, this.priority);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static NameStage builder() {
    return new Builder();
  }

  public interface NameStage {
    /**
     * <p>Human-readable name for the environment.</p>
     */
    KeyStage name(@NotNull String name);

    Builder from(AdminEnvironment other);
  }

  public interface KeyStage {
    /**
     * <p>Machine-readable identifier for the environment.</p>
     */
    PriorityStage key(@NotNull String key);
  }

  public interface PriorityStage {
    /**
     * <p>Environment precedence. Lower numbers take priority. Production is always 1.</p>
     */
    _FinalStage priority(int priority);
  }

  public interface _FinalStage {
    AdminEnvironment build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements NameStage, KeyStage, PriorityStage, _FinalStage {
    private String name;

    private String key;

    private int priority;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(AdminEnvironment other) {
      name(other.getName());
      key(other.getKey());
      priority(other.getPriority());
      return this;
    }

    /**
     * <p>Human-readable name for the environment.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("name")
    public KeyStage name(@NotNull String name) {
      this.name = Objects.requireNonNull(name, "name must not be null");
      return this;
    }

    /**
     * <p>Machine-readable identifier for the environment.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("key")
    public PriorityStage key(@NotNull String key) {
      this.key = Objects.requireNonNull(key, "key must not be null");
      return this;
    }

    /**
     * <p>Environment precedence. Lower numbers take priority. Production is always 1.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("priority")
    public _FinalStage priority(int priority) {
      this.priority = priority;
      return this;
    }

    @java.lang.Override
    public AdminEnvironment build() {
      return new AdminEnvironment(name, key, priority, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
