package so.trophy.src.main.java.types;

/**
 * This file was auto-generated by Fern from our API Definition.
 */


import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import so.trophy.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = BatchMetricEvent.Builder.class
)
public final class BatchMetricEvent {
  private final String key;

  private final BatchMetricEventUser user;

  private final double value;

  private final Optional<Map<String, String>> attributes;

  private final Optional<String> idempotencyKey;

  private final Map<String, Object> additionalProperties;

  private BatchMetricEvent(String key, BatchMetricEventUser user, double value,
      Optional<Map<String, String>> attributes, Optional<String> idempotencyKey,
      Map<String, Object> additionalProperties) {
    this.key = key;
    this.user = user;
    this.value = value;
    this.attributes = attributes;
    this.idempotencyKey = idempotencyKey;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Unique reference of the metric as set when created.
   */
  @JsonProperty("key")
  public String getKey() {
    return key;
  }

  /**
   * @return The user that triggered the event.
   */
  @JsonProperty("user")
  public BatchMetricEventUser getUser() {
    return user;
  }

  /**
   * @return The value to add to the user's current total for the given metric.
   */
  @JsonProperty("value")
  public double getValue() {
    return value;
  }

  /**
   * @return Event attributes as key-value pairs. Keys must match existing event attributes set up in the Trophy dashboard.
   */
  @JsonProperty("attributes")
  public Optional<Map<String, String>> getAttributes() {
    return attributes;
  }

  /**
   * @return Optional idempotency key for this event. When provided, the event is ignored if another event with the same idempotency key has already  been processed.
   */
  @JsonProperty("idempotencyKey")
  public Optional<String> getIdempotencyKey() {
    return idempotencyKey;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof BatchMetricEvent && equalTo((BatchMetricEvent) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(BatchMetricEvent other) {
    return key.equals(other.key) && user.equals(other.user) && value == other.value && attributes.equals(other.attributes) && idempotencyKey.equals(other.idempotencyKey);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.key, this.user, this.value, this.attributes, this.idempotencyKey);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static KeyStage builder() {
    return new Builder();
  }

  public interface KeyStage {
    /**
     * <p>Unique reference of the metric as set when created.</p>
     */
    UserStage key(@NotNull String key);

    Builder from(BatchMetricEvent other);
  }

  public interface UserStage {
    /**
     * <p>The user that triggered the event.</p>
     */
    ValueStage user(@NotNull BatchMetricEventUser user);
  }

  public interface ValueStage {
    /**
     * <p>The value to add to the user's current total for the given metric.</p>
     */
    _FinalStage value(double value);
  }

  public interface _FinalStage {
    BatchMetricEvent build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Event attributes as key-value pairs. Keys must match existing event attributes set up in the Trophy dashboard.</p>
     */
    _FinalStage attributes(Optional<Map<String, String>> attributes);

    _FinalStage attributes(Map<String, String> attributes);

    /**
     * <p>Optional idempotency key for this event. When provided, the event is ignored if another event with the same idempotency key has already  been processed.</p>
     */
    _FinalStage idempotencyKey(Optional<String> idempotencyKey);

    _FinalStage idempotencyKey(String idempotencyKey);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements KeyStage, UserStage, ValueStage, _FinalStage {
    private String key;

    private BatchMetricEventUser user;

    private double value;

    private Optional<String> idempotencyKey = Optional.empty();

    private Optional<Map<String, String>> attributes = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(BatchMetricEvent other) {
      key(other.getKey());
      user(other.getUser());
      value(other.getValue());
      attributes(other.getAttributes());
      idempotencyKey(other.getIdempotencyKey());
      return this;
    }

    /**
     * <p>Unique reference of the metric as set when created.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("key")
    public UserStage key(@NotNull String key) {
      this.key = Objects.requireNonNull(key, "key must not be null");
      return this;
    }

    /**
     * <p>The user that triggered the event.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("user")
    public ValueStage user(@NotNull BatchMetricEventUser user) {
      this.user = Objects.requireNonNull(user, "user must not be null");
      return this;
    }

    /**
     * <p>The value to add to the user's current total for the given metric.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("value")
    public _FinalStage value(double value) {
      this.value = value;
      return this;
    }

    /**
     * <p>Optional idempotency key for this event. When provided, the event is ignored if another event with the same idempotency key has already  been processed.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage idempotencyKey(String idempotencyKey) {
      this.idempotencyKey = Optional.ofNullable(idempotencyKey);
      return this;
    }

    /**
     * <p>Optional idempotency key for this event. When provided, the event is ignored if another event with the same idempotency key has already  been processed.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "idempotencyKey",
        nulls = Nulls.SKIP
    )
    public _FinalStage idempotencyKey(Optional<String> idempotencyKey) {
      this.idempotencyKey = idempotencyKey;
      return this;
    }

    /**
     * <p>Event attributes as key-value pairs. Keys must match existing event attributes set up in the Trophy dashboard.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage attributes(Map<String, String> attributes) {
      this.attributes = Optional.ofNullable(attributes);
      return this;
    }

    /**
     * <p>Event attributes as key-value pairs. Keys must match existing event attributes set up in the Trophy dashboard.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "attributes",
        nulls = Nulls.SKIP
    )
    public _FinalStage attributes(Optional<Map<String, String>> attributes) {
      this.attributes = attributes;
      return this;
    }

    @java.lang.Override
    public BatchMetricEvent build() {
      return new BatchMetricEvent(key, user, value, attributes, idempotencyKey, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
