package so.trophy.src.main.java.types;

/**
 * This file was auto-generated by Fern from our API Definition.
 */


import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import so.trophy.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreatedApplicationKey.Builder.class
)
public final class CreatedApplicationKey {
  private final String id;

  private final String userId;

  private final String key;

  private final String prefix;

  private final Map<String, Object> additionalProperties;

  private CreatedApplicationKey(String id, String userId, String key, String prefix,
      Map<String, Object> additionalProperties) {
    this.id = id;
    this.userId = userId;
    this.key = key;
    this.prefix = prefix;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The unique identifier of the API key. Use this ID to delete the key.
   */
  @JsonProperty("id")
  public String getId() {
    return id;
  }

  /**
   * @return The user ID the key is scoped to.
   */
  @JsonProperty("userId")
  public String getUserId() {
    return userId;
  }

  /**
   * @return The full API key value. This is only returned once at creation time and cannot be retrieved again.
   */
  @JsonProperty("key")
  public String getKey() {
    return key;
  }

  /**
   * @return The key prefix used for cache lookup.
   */
  @JsonProperty("prefix")
  public String getPrefix() {
    return prefix;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreatedApplicationKey && equalTo((CreatedApplicationKey) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreatedApplicationKey other) {
    return id.equals(other.id) && userId.equals(other.userId) && key.equals(other.key) && prefix.equals(other.prefix);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.userId, this.key, this.prefix);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static IdStage builder() {
    return new Builder();
  }

  public interface IdStage {
    /**
     * <p>The unique identifier of the API key. Use this ID to delete the key.</p>
     */
    UserIdStage id(@NotNull String id);

    Builder from(CreatedApplicationKey other);
  }

  public interface UserIdStage {
    /**
     * <p>The user ID the key is scoped to.</p>
     */
    KeyStage userId(@NotNull String userId);
  }

  public interface KeyStage {
    /**
     * <p>The full API key value. This is only returned once at creation time and cannot be retrieved again.</p>
     */
    PrefixStage key(@NotNull String key);
  }

  public interface PrefixStage {
    /**
     * <p>The key prefix used for cache lookup.</p>
     */
    _FinalStage prefix(@NotNull String prefix);
  }

  public interface _FinalStage {
    CreatedApplicationKey build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements IdStage, UserIdStage, KeyStage, PrefixStage, _FinalStage {
    private String id;

    private String userId;

    private String key;

    private String prefix;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CreatedApplicationKey other) {
      id(other.getId());
      userId(other.getUserId());
      key(other.getKey());
      prefix(other.getPrefix());
      return this;
    }

    /**
     * <p>The unique identifier of the API key. Use this ID to delete the key.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("id")
    public UserIdStage id(@NotNull String id) {
      this.id = Objects.requireNonNull(id, "id must not be null");
      return this;
    }

    /**
     * <p>The user ID the key is scoped to.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("userId")
    public KeyStage userId(@NotNull String userId) {
      this.userId = Objects.requireNonNull(userId, "userId must not be null");
      return this;
    }

    /**
     * <p>The full API key value. This is only returned once at creation time and cannot be retrieved again.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("key")
    public PrefixStage key(@NotNull String key) {
      this.key = Objects.requireNonNull(key, "key must not be null");
      return this;
    }

    /**
     * <p>The key prefix used for cache lookup.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("prefix")
    public _FinalStage prefix(@NotNull String prefix) {
      this.prefix = Objects.requireNonNull(prefix, "prefix must not be null");
      return this;
    }

    @java.lang.Override
    public CreatedApplicationKey build() {
      return new CreatedApplicationKey(id, userId, key, prefix, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
