package so.trophy.src.main.java.types;

/**
 * This file was auto-generated by Fern from our API Definition.
 */


import java.lang.Integer;
import java.util.Optional;

public interface IUserLeaderboardResponse extends ILeaderboardResponse {
  Optional<Integer> getRank();

  Optional<Integer> getValue();
}
