package so.trophy.src.main.java.types;

/**
 * This file was auto-generated by Fern from our API Definition.
 */


import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import so.trophy.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = WebhooksEmailsReactivationDuePayload.Builder.class
)
public final class WebhooksEmailsReactivationDuePayload {
  private final OffsetDateTime timestamp;

  private final User user;

  private final WebhooksEmailsReactivationDuePayloadReactivation reactivation;

  private final Map<String, Object> additionalProperties;

  private WebhooksEmailsReactivationDuePayload(OffsetDateTime timestamp, User user,
      WebhooksEmailsReactivationDuePayloadReactivation reactivation,
      Map<String, Object> additionalProperties) {
    this.timestamp = timestamp;
    this.user = user;
    this.reactivation = reactivation;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The webhook event type.
   */
  @JsonProperty("type")
  public String getType() {
    return "emails.reactivation_due";
  }

  /**
   * @return The time the webhook was sent.
   */
  @JsonProperty("timestamp")
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }

  /**
   * @return The user the reactivation message is due for.
   */
  @JsonProperty("user")
  public User getUser() {
    return user;
  }

  /**
   * @return Details about the reactivation message.
   */
  @JsonProperty("reactivation")
  public WebhooksEmailsReactivationDuePayloadReactivation getReactivation() {
    return reactivation;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof WebhooksEmailsReactivationDuePayload && equalTo((WebhooksEmailsReactivationDuePayload) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(WebhooksEmailsReactivationDuePayload other) {
    return timestamp.equals(other.timestamp) && user.equals(other.user) && reactivation.equals(other.reactivation);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.timestamp, this.user, this.reactivation);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static TimestampStage builder() {
    return new Builder();
  }

  public interface TimestampStage {
    /**
     * <p>The time the webhook was sent.</p>
     */
    UserStage timestamp(@NotNull OffsetDateTime timestamp);

    Builder from(WebhooksEmailsReactivationDuePayload other);
  }

  public interface UserStage {
    /**
     * <p>The user the reactivation message is due for.</p>
     */
    ReactivationStage user(@NotNull User user);
  }

  public interface ReactivationStage {
    /**
     * <p>Details about the reactivation message.</p>
     */
    _FinalStage reactivation(
        @NotNull WebhooksEmailsReactivationDuePayloadReactivation reactivation);
  }

  public interface _FinalStage {
    WebhooksEmailsReactivationDuePayload build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements TimestampStage, UserStage, ReactivationStage, _FinalStage {
    private OffsetDateTime timestamp;

    private User user;

    private WebhooksEmailsReactivationDuePayloadReactivation reactivation;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(WebhooksEmailsReactivationDuePayload other) {
      timestamp(other.getTimestamp());
      user(other.getUser());
      reactivation(other.getReactivation());
      return this;
    }

    /**
     * <p>The time the webhook was sent.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("timestamp")
    public UserStage timestamp(@NotNull OffsetDateTime timestamp) {
      this.timestamp = Objects.requireNonNull(timestamp, "timestamp must not be null");
      return this;
    }

    /**
     * <p>The user the reactivation message is due for.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("user")
    public ReactivationStage user(@NotNull User user) {
      this.user = Objects.requireNonNull(user, "user must not be null");
      return this;
    }

    /**
     * <p>Details about the reactivation message.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("reactivation")
    public _FinalStage reactivation(
        @NotNull WebhooksEmailsReactivationDuePayloadReactivation reactivation) {
      this.reactivation = Objects.requireNonNull(reactivation, "reactivation must not be null");
      return this;
    }

    @java.lang.Override
    public WebhooksEmailsReactivationDuePayload build() {
      return new WebhooksEmailsReactivationDuePayload(timestamp, user, reactivation, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
