package so.trophy.resources.points;

/**
 * This file was auto-generated by Fern from our API Definition.
 */


import so.trophy.core.ClientOptions;
import so.trophy.core.RequestOptions;
import java.lang.String;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import so.trophy.resources.points.requests.PointsBoostsRequest;
import so.trophy.resources.points.requests.PointsSummaryRequest;
import so.trophy.types.PointsBoost;
import so.trophy.types.PointsRange;
import so.trophy.types.PointsSystemResponse;

public class AsyncPointsClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawPointsClient rawClient;

  public AsyncPointsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawPointsClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawPointsClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Get a breakdown of the number of users with points in each range.
   */
  public CompletableFuture<List<PointsRange>> summary(String key) {
    return this.rawClient.summary(key).thenApply(response -> response.body());
  }

  /**
   * Get a breakdown of the number of users with points in each range.
   */
  public CompletableFuture<List<PointsRange>> summary(String key, PointsSummaryRequest request) {
    return this.rawClient.summary(key, request).thenApply(response -> response.body());
  }

  /**
   * Get a breakdown of the number of users with points in each range.
   */
  public CompletableFuture<List<PointsRange>> summary(String key, PointsSummaryRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.summary(key, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get a points system with its triggers.
   */
  public CompletableFuture<PointsSystemResponse> system(String key) {
    return this.rawClient.system(key).thenApply(response -> response.body());
  }

  /**
   * Get a points system with its triggers.
   */
  public CompletableFuture<PointsSystemResponse> system(String key, RequestOptions requestOptions) {
    return this.rawClient.system(key, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get all global boosts for a points system. Finished boosts are excluded by default.
   */
  public CompletableFuture<List<PointsBoost>> boosts(String key) {
    return this.rawClient.boosts(key).thenApply(response -> response.body());
  }

  /**
   * Get all global boosts for a points system. Finished boosts are excluded by default.
   */
  public CompletableFuture<List<PointsBoost>> boosts(String key, PointsBoostsRequest request) {
    return this.rawClient.boosts(key, request).thenApply(response -> response.body());
  }

  /**
   * Get all global boosts for a points system. Finished boosts are excluded by default.
   */
  public CompletableFuture<List<PointsBoost>> boosts(String key, PointsBoostsRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.boosts(key, request, requestOptions).thenApply(response -> response.body());
  }
}
