package so.trophy.src.main.java.resources.admin.applicationapikeys;

/**
 * This file was auto-generated by Fern from our API Definition.
 */


import so.trophy.core.ClientOptions;
import so.trophy.core.RequestOptions;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import so.trophy.resources.admin.applicationapikeys.requests.ApplicationApiKeysDeleteRequest;
import so.trophy.types.CreateApplicationKeyRequestItem;
import so.trophy.types.CreateApplicationKeysResponse;
import so.trophy.types.DeleteApplicationKeysResponse;

public class AsyncApplicationApiKeysClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawApplicationApiKeysClient rawClient;

  public AsyncApplicationApiKeysClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawApplicationApiKeysClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawApplicationApiKeysClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Create application API keys scoped to specific users. Each key can only perform operations on behalf of the user it was created for.
   */
  public CompletableFuture<CreateApplicationKeysResponse> create(
      List<CreateApplicationKeyRequestItem> request) {
    return this.rawClient.create(request).thenApply(response -> response.body());
  }

  /**
   * Create application API keys scoped to specific users. Each key can only perform operations on behalf of the user it was created for.
   */
  public CompletableFuture<CreateApplicationKeysResponse> create(
      List<CreateApplicationKeyRequestItem> request, RequestOptions requestOptions) {
    return this.rawClient.create(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Delete application API keys by ID.
   */
  public CompletableFuture<DeleteApplicationKeysResponse> delete() {
    return this.rawClient.delete().thenApply(response -> response.body());
  }

  /**
   * Delete application API keys by ID.
   */
  public CompletableFuture<DeleteApplicationKeysResponse> delete(RequestOptions requestOptions) {
    return this.rawClient.delete(requestOptions).thenApply(response -> response.body());
  }

  /**
   * Delete application API keys by ID.
   */
  public CompletableFuture<DeleteApplicationKeysResponse> delete(
      ApplicationApiKeysDeleteRequest request) {
    return this.rawClient.delete(request).thenApply(response -> response.body());
  }

  /**
   * Delete application API keys by ID.
   */
  public CompletableFuture<DeleteApplicationKeysResponse> delete(
      ApplicationApiKeysDeleteRequest request, RequestOptions requestOptions) {
    return this.rawClient.delete(request, requestOptions).thenApply(response -> response.body());
  }
}
