package so.trophy.resources.admin.points.levels;

/**
 * This file was auto-generated by Fern from our API Definition.
 */


import so.trophy.core.ClientOptions;
import so.trophy.core.RequestOptions;
import java.lang.String;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import so.trophy.resources.admin.points.levels.requests.LevelsDeleteRequest;
import so.trophy.resources.admin.points.levels.requests.LevelsListRequest;
import so.trophy.types.AdminPointsLevel;
import so.trophy.types.CreatePointsLevelRequestItem;
import so.trophy.types.CreatePointsLevelsResponse;
import so.trophy.types.DeletePointsLevelsResponse;
import so.trophy.types.PatchPointsLevelsRequestItem;
import so.trophy.types.PatchPointsLevelsResponse;

public class AsyncLevelsClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawLevelsClient rawClient;

  public AsyncLevelsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawLevelsClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawLevelsClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * List points levels for a system.
   */
  public CompletableFuture<List<AdminPointsLevel>> list(String systemId) {
    return this.rawClient.list(systemId).thenApply(response -> response.body());
  }

  /**
   * List points levels for a system.
   */
  public CompletableFuture<List<AdminPointsLevel>> list(String systemId,
      LevelsListRequest request) {
    return this.rawClient.list(systemId, request).thenApply(response -> response.body());
  }

  /**
   * List points levels for a system.
   */
  public CompletableFuture<List<AdminPointsLevel>> list(String systemId, LevelsListRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.list(systemId, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Create points levels. Maximum 100 levels per request.
   */
  public CompletableFuture<CreatePointsLevelsResponse> create(String systemId,
      List<CreatePointsLevelRequestItem> request) {
    return this.rawClient.create(systemId, request).thenApply(response -> response.body());
  }

  /**
   * Create points levels. Maximum 100 levels per request.
   */
  public CompletableFuture<CreatePointsLevelsResponse> create(String systemId,
      List<CreatePointsLevelRequestItem> request, RequestOptions requestOptions) {
    return this.rawClient.create(systemId, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Delete multiple points levels by ID.
   */
  public CompletableFuture<DeletePointsLevelsResponse> delete(String systemId) {
    return this.rawClient.delete(systemId).thenApply(response -> response.body());
  }

  /**
   * Delete multiple points levels by ID.
   */
  public CompletableFuture<DeletePointsLevelsResponse> delete(String systemId,
      LevelsDeleteRequest request) {
    return this.rawClient.delete(systemId, request).thenApply(response -> response.body());
  }

  /**
   * Delete multiple points levels by ID.
   */
  public CompletableFuture<DeletePointsLevelsResponse> delete(String systemId,
      LevelsDeleteRequest request, RequestOptions requestOptions) {
    return this.rawClient.delete(systemId, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Update multiple points levels. Each item must include an ID. <code>key</code> cannot be changed.
   */
  public CompletableFuture<PatchPointsLevelsResponse> update(String systemId,
      List<PatchPointsLevelsRequestItem> request) {
    return this.rawClient.update(systemId, request).thenApply(response -> response.body());
  }

  /**
   * Update multiple points levels. Each item must include an ID. <code>key</code> cannot be changed.
   */
  public CompletableFuture<PatchPointsLevelsResponse> update(String systemId,
      List<PatchPointsLevelsRequestItem> request, RequestOptions requestOptions) {
    return this.rawClient.update(systemId, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get a single points level by ID.
   */
  public CompletableFuture<AdminPointsLevel> get(String systemId, String id) {
    return this.rawClient.get(systemId, id).thenApply(response -> response.body());
  }

  /**
   * Get a single points level by ID.
   */
  public CompletableFuture<AdminPointsLevel> get(String systemId, String id,
      RequestOptions requestOptions) {
    return this.rawClient.get(systemId, id, requestOptions).thenApply(response -> response.body());
  }
}
