package so.trophy.resources.admin.points.boosts;

/**
 * This file was auto-generated by Fern from our API Definition.
 */


import so.trophy.core.ClientOptions;
import so.trophy.core.RequestOptions;
import java.util.concurrent.CompletableFuture;
import so.trophy.resources.admin.points.boosts.requests.BoostsDeleteRequest;
import so.trophy.resources.admin.points.boosts.requests.CreatePointsBoostsRequest;
import so.trophy.types.CreatePointsBoostsResponse;
import so.trophy.types.DeletePointsBoostsResponse;

public class AsyncBoostsClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawBoostsClient rawClient;

  public AsyncBoostsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawBoostsClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawBoostsClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Create points boosts for multiple users.
   */
  public CompletableFuture<CreatePointsBoostsResponse> create(CreatePointsBoostsRequest request) {
    return this.rawClient.create(request).thenApply(response -> response.body());
  }

  /**
   * Create points boosts for multiple users.
   */
  public CompletableFuture<CreatePointsBoostsResponse> create(CreatePointsBoostsRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.create(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Delete multiple points boosts by ID.
   */
  public CompletableFuture<DeletePointsBoostsResponse> delete() {
    return this.rawClient.delete().thenApply(response -> response.body());
  }

  /**
   * Delete multiple points boosts by ID.
   */
  public CompletableFuture<DeletePointsBoostsResponse> delete(BoostsDeleteRequest request) {
    return this.rawClient.delete(request).thenApply(response -> response.body());
  }

  /**
   * Delete multiple points boosts by ID.
   */
  public CompletableFuture<DeletePointsBoostsResponse> delete(BoostsDeleteRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.delete(request, requestOptions).thenApply(response -> response.body());
  }
}
