package so.trophy.resources.admin.points.boosts;

/**
 * This file was auto-generated by Fern from our API Definition.
 */


import so.trophy.core.ClientOptions;
import so.trophy.core.RequestOptions;
import so.trophy.resources.admin.points.boosts.requests.BoostsDeleteRequest;
import so.trophy.resources.admin.points.boosts.requests.CreatePointsBoostsRequest;
import so.trophy.types.CreatePointsBoostsResponse;
import so.trophy.types.DeletePointsBoostsResponse;

public class BoostsClient {
  protected final ClientOptions clientOptions;

  private final RawBoostsClient rawClient;

  public BoostsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new RawBoostsClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public RawBoostsClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Create points boosts for multiple users.
   */
  public CreatePointsBoostsResponse create(CreatePointsBoostsRequest request) {
    return this.rawClient.create(request).body();
  }

  /**
   * Create points boosts for multiple users.
   */
  public CreatePointsBoostsResponse create(CreatePointsBoostsRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.create(request, requestOptions).body();
  }

  /**
   * Delete multiple points boosts by ID.
   */
  public DeletePointsBoostsResponse delete() {
    return this.rawClient.delete().body();
  }

  /**
   * Delete multiple points boosts by ID.
   */
  public DeletePointsBoostsResponse delete(BoostsDeleteRequest request) {
    return this.rawClient.delete(request).body();
  }

  /**
   * Delete multiple points boosts by ID.
   */
  public DeletePointsBoostsResponse delete(BoostsDeleteRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.delete(request, requestOptions).body();
  }
}
