package so.trophy.resources.users.requests;

/**
 * This file was auto-generated by Fern from our API Definition.
 */


import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import so.trophy.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import so.trophy.types.NotificationPreferences;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = UpdateUserPreferencesRequest.Builder.class
)
public final class UpdateUserPreferencesRequest {
  private final Optional<NotificationPreferences> notifications;

  private final Map<String, Object> additionalProperties;

  private UpdateUserPreferencesRequest(Optional<NotificationPreferences> notifications,
      Map<String, Object> additionalProperties) {
    this.notifications = notifications;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("notifications")
  public Optional<NotificationPreferences> getNotifications() {
    return notifications;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof UpdateUserPreferencesRequest && equalTo((UpdateUserPreferencesRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(UpdateUserPreferencesRequest other) {
    return notifications.equals(other.notifications);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.notifications);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<NotificationPreferences> notifications = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(UpdateUserPreferencesRequest other) {
      notifications(other.getNotifications());
      return this;
    }

    @JsonSetter(
        value = "notifications",
        nulls = Nulls.SKIP
    )
    public Builder notifications(Optional<NotificationPreferences> notifications) {
      this.notifications = notifications;
      return this;
    }

    public Builder notifications(NotificationPreferences notifications) {
      this.notifications = Optional.ofNullable(notifications);
      return this;
    }

    public UpdateUserPreferencesRequest build() {
      return new UpdateUserPreferencesRequest(notifications, additionalProperties);
    }
  }
}
