package so.trophy.resources.admin.leaderboards;

/**
 * This file was auto-generated by Fern from our API Definition.
 */


import so.trophy.core.ClientOptions;
import so.trophy.core.RequestOptions;
import java.lang.String;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import so.trophy.resources.admin.leaderboards.requests.LeaderboardsDeleteRequest;
import so.trophy.resources.admin.leaderboards.requests.LeaderboardsListRequest;
import so.trophy.types.AdminLeaderboard;
import so.trophy.types.CreateLeaderboardRequestItem;
import so.trophy.types.CreateLeaderboardsResponse;
import so.trophy.types.DeleteLeaderboardsResponse;
import so.trophy.types.UpdateLeaderboardRequestItem;
import so.trophy.types.UpdateLeaderboardsResponse;

public class AsyncLeaderboardsClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawLeaderboardsClient rawClient;

  public AsyncLeaderboardsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawLeaderboardsClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawLeaderboardsClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * List leaderboards.
   */
  public CompletableFuture<List<AdminLeaderboard>> list() {
    return this.rawClient.list().thenApply(response -> response.body());
  }

  /**
   * List leaderboards.
   */
  public CompletableFuture<List<AdminLeaderboard>> list(LeaderboardsListRequest request) {
    return this.rawClient.list(request).thenApply(response -> response.body());
  }

  /**
   * List leaderboards.
   */
  public CompletableFuture<List<AdminLeaderboard>> list(LeaderboardsListRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.list(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Create leaderboards. Maximum 100 leaderboards per request.
   */
  public CompletableFuture<CreateLeaderboardsResponse> create(
      List<CreateLeaderboardRequestItem> request) {
    return this.rawClient.create(request).thenApply(response -> response.body());
  }

  /**
   * Create leaderboards. Maximum 100 leaderboards per request.
   */
  public CompletableFuture<CreateLeaderboardsResponse> create(
      List<CreateLeaderboardRequestItem> request, RequestOptions requestOptions) {
    return this.rawClient.create(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Delete leaderboards by ID.
   */
  public CompletableFuture<DeleteLeaderboardsResponse> delete() {
    return this.rawClient.delete().thenApply(response -> response.body());
  }

  /**
   * Delete leaderboards by ID.
   */
  public CompletableFuture<DeleteLeaderboardsResponse> delete(LeaderboardsDeleteRequest request) {
    return this.rawClient.delete(request).thenApply(response -> response.body());
  }

  /**
   * Delete leaderboards by ID.
   */
  public CompletableFuture<DeleteLeaderboardsResponse> delete(LeaderboardsDeleteRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.delete(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Update leaderboards by ID. Updating <code>status</code> behaves the same as activating, scheduling, deactivating, or finishing a leaderboard in the dashboard.
   */
  public CompletableFuture<UpdateLeaderboardsResponse> update(
      List<UpdateLeaderboardRequestItem> request) {
    return this.rawClient.update(request).thenApply(response -> response.body());
  }

  /**
   * Update leaderboards by ID. Updating <code>status</code> behaves the same as activating, scheduling, deactivating, or finishing a leaderboard in the dashboard.
   */
  public CompletableFuture<UpdateLeaderboardsResponse> update(
      List<UpdateLeaderboardRequestItem> request, RequestOptions requestOptions) {
    return this.rawClient.update(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get a leaderboard by ID.
   */
  public CompletableFuture<AdminLeaderboard> get(String id) {
    return this.rawClient.get(id).thenApply(response -> response.body());
  }

  /**
   * Get a leaderboard by ID.
   */
  public CompletableFuture<AdminLeaderboard> get(String id, RequestOptions requestOptions) {
    return this.rawClient.get(id, requestOptions).thenApply(response -> response.body());
  }
}
