package so.trophy.resources.admin.points;

/**
 * This file was auto-generated by Fern from our API Definition.
 */


import so.trophy.core.ClientOptions;
import so.trophy.core.Suppliers;
import java.util.function.Supplier;
import so.trophy.resources.admin.points.boosts.AsyncBoostsClient;

public class AsyncPointsClient {
  protected final ClientOptions clientOptions;

  protected final Supplier<AsyncBoostsClient> boostsClient;

  public AsyncPointsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.boostsClient = Suppliers.memoize(() -> new AsyncBoostsClient(clientOptions));
  }

  public AsyncBoostsClient boosts() {
    return this.boostsClient.get();
  }
}
