package so.trophy.resources.admin.streaks;

/**
 * This file was auto-generated by Fern from our API Definition.
 */


import so.trophy.core.ClientOptions;
import so.trophy.core.Suppliers;
import java.util.function.Supplier;
import so.trophy.resources.admin.streaks.freezes.FreezesClient;

public class StreaksClient {
  protected final ClientOptions clientOptions;

  protected final Supplier<FreezesClient> freezesClient;

  public StreaksClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.freezesClient = Suppliers.memoize(() -> new FreezesClient(clientOptions));
  }

  public FreezesClient freezes() {
    return this.freezesClient.get();
  }
}
