package so.trophy.resources.admin.points.systems;

/**
 * This file was auto-generated by Fern from our API Definition.
 */


import so.trophy.core.ClientOptions;
import so.trophy.core.RequestOptions;
import java.lang.String;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import so.trophy.resources.admin.points.systems.requests.SystemsDeleteRequest;
import so.trophy.resources.admin.points.systems.requests.SystemsListRequest;
import so.trophy.types.AdminPointsSystem;
import so.trophy.types.CreatePointsSystemRequestItem;
import so.trophy.types.CreatePointsSystemsResponse;
import so.trophy.types.DeletePointsSystemsResponse;
import so.trophy.types.UpdatePointsSystemRequestItem;
import so.trophy.types.UpdatePointsSystemsResponse;

public class AsyncSystemsClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawSystemsClient rawClient;

  public AsyncSystemsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawSystemsClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawSystemsClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * List points systems.
   */
  public CompletableFuture<List<AdminPointsSystem>> list() {
    return this.rawClient.list().thenApply(response -> response.body());
  }

  /**
   * List points systems.
   */
  public CompletableFuture<List<AdminPointsSystem>> list(SystemsListRequest request) {
    return this.rawClient.list(request).thenApply(response -> response.body());
  }

  /**
   * List points systems.
   */
  public CompletableFuture<List<AdminPointsSystem>> list(SystemsListRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.list(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Create points systems. Optionally include sub-entities (levels, boosts, triggers) in each system payload to create them alongside the system.
   */
  public CompletableFuture<CreatePointsSystemsResponse> create(
      List<CreatePointsSystemRequestItem> request) {
    return this.rawClient.create(request).thenApply(response -> response.body());
  }

  /**
   * Create points systems. Optionally include sub-entities (levels, boosts, triggers) in each system payload to create them alongside the system.
   */
  public CompletableFuture<CreatePointsSystemsResponse> create(
      List<CreatePointsSystemRequestItem> request, RequestOptions requestOptions) {
    return this.rawClient.create(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Delete (archive) points systems by ID.
   */
  public CompletableFuture<DeletePointsSystemsResponse> delete() {
    return this.rawClient.delete().thenApply(response -> response.body());
  }

  /**
   * Delete (archive) points systems by ID.
   */
  public CompletableFuture<DeletePointsSystemsResponse> delete(SystemsDeleteRequest request) {
    return this.rawClient.delete(request).thenApply(response -> response.body());
  }

  /**
   * Delete (archive) points systems by ID.
   */
  public CompletableFuture<DeletePointsSystemsResponse> delete(SystemsDeleteRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.delete(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Update points systems by ID.
   */
  public CompletableFuture<UpdatePointsSystemsResponse> update(
      List<UpdatePointsSystemRequestItem> request) {
    return this.rawClient.update(request).thenApply(response -> response.body());
  }

  /**
   * Update points systems by ID.
   */
  public CompletableFuture<UpdatePointsSystemsResponse> update(
      List<UpdatePointsSystemRequestItem> request, RequestOptions requestOptions) {
    return this.rawClient.update(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get a points system by ID.
   */
  public CompletableFuture<AdminPointsSystem> get(String id) {
    return this.rawClient.get(id).thenApply(response -> response.body());
  }

  /**
   * Get a points system by ID.
   */
  public CompletableFuture<AdminPointsSystem> get(String id, RequestOptions requestOptions) {
    return this.rawClient.get(id, requestOptions).thenApply(response -> response.body());
  }
}
