package so.trophy.src.main.java.resources.admin.streaks.settings;

/**
 * This file was auto-generated by Fern from our API Definition.
 */


import com.fasterxml.jackson.core.JsonProcessingException;
import so.trophy.core.ClientOptions;
import so.trophy.core.MediaTypes;
import so.trophy.core.ObjectMappers;
import so.trophy.core.RequestOptions;
import so.trophy.core.RetryInterceptor;
import so.trophy.core.TrophyApiApiException;
import so.trophy.core.TrophyApiException;
import so.trophy.core.TrophyApiHttpResponse;
import so.trophy.errors.UnauthorizedError;
import so.trophy.errors.UnprocessableEntityError;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;
import so.trophy.resources.admin.streaks.settings.requests.UpdateStreakSettingsRequest;
import so.trophy.types.StreakSettings;

public class AsyncRawSettingsClient {
  protected final ClientOptions clientOptions;

  public AsyncRawSettingsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * Get the organization's streak configuration.
   */
  public CompletableFuture<TrophyApiHttpResponse<StreakSettings>> get() {
    return get(null);
  }

  /**
   * Get the organization's streak configuration.
   */
  public CompletableFuture<TrophyApiHttpResponse<StreakSettings>> get(
      RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getAdminURL()).newBuilder()

      .addPathSegments("streaks/settings");if (requestOptions != null) {
        requestOptions.getQueryParameters().forEach((_key, _value) -> {
          httpUrl.addQueryParameter(_key, _value);
        } );
      }
      Request okhttpRequest = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json")
        .build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
        okhttpRequest = okhttpRequest.newBuilder().tag(RetryInterceptor.MaxRetriesOverride.class, new RetryInterceptor.MaxRetriesOverride(requestOptions.getMaxRetries().get())).build();
      }
      CompletableFuture<TrophyApiHttpResponse<StreakSettings>> future = new CompletableFuture<>();
      client.newCall(okhttpRequest).enqueue(new Callback() {
        @Override
        public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
          try (ResponseBody responseBody = response.body()) {
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
              future.complete(new TrophyApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, StreakSettings.class), response));
              return;
            }
            try {
              switch (response.code()) {
                case 401:future.completeExceptionally(new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                return;
                case 422:future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                return;
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            future.completeExceptionally(new TrophyApiApiException("Error with status code " + response.code(), response.code(), errorBody, response));
            return;
          }
          catch (IOException e) {
            future.completeExceptionally(new TrophyApiException("Network error executing HTTP request", e));
          }
        }

        @Override
        public void onFailure(@NotNull Call call, @NotNull IOException e) {
          future.completeExceptionally(new TrophyApiException("Network error executing HTTP request", e));
        }
      });
      return future;
    }

    /**
     * Update the organization's streak configuration.
     */
    public CompletableFuture<TrophyApiHttpResponse<StreakSettings>> update() {
      return update(UpdateStreakSettingsRequest.builder().build());
    }

    /**
     * Update the organization's streak configuration.
     */
    public CompletableFuture<TrophyApiHttpResponse<StreakSettings>> update(
        RequestOptions requestOptions) {
      return update(UpdateStreakSettingsRequest.builder().build(),requestOptions);
    }

    /**
     * Update the organization's streak configuration.
     */
    public CompletableFuture<TrophyApiHttpResponse<StreakSettings>> update(
        UpdateStreakSettingsRequest request) {
      return update(request,null);
    }

    /**
     * Update the organization's streak configuration.
     */
    public CompletableFuture<TrophyApiHttpResponse<StreakSettings>> update(
        UpdateStreakSettingsRequest request, RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getAdminURL()).newBuilder()

        .addPathSegments("streaks/settings");if (requestOptions != null) {
          requestOptions.getQueryParameters().forEach((_key, _value) -> {
            httpUrl.addQueryParameter(_key, _value);
          } );
        }
        RequestBody body;
        try {
          body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        }
        catch(JsonProcessingException e) {
          throw new TrophyApiException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
          .url(httpUrl.build())
          .method("PATCH", body)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Content-Type", "application/json")
          .addHeader("Accept", "application/json")
          .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
          okhttpRequest = okhttpRequest.newBuilder().tag(RetryInterceptor.MaxRetriesOverride.class, new RetryInterceptor.MaxRetriesOverride(requestOptions.getMaxRetries().get())).build();
        }
        CompletableFuture<TrophyApiHttpResponse<StreakSettings>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
          @Override
          public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
            try (ResponseBody responseBody = response.body()) {
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              if (response.isSuccessful()) {
                future.complete(new TrophyApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, StreakSettings.class), response));
                return;
              }
              try {
                switch (response.code()) {
                  case 401:future.completeExceptionally(new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                  return;
                  case 422:future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                  return;
                }
              }
              catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
              }
              Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
              future.completeExceptionally(new TrophyApiApiException("Error with status code " + response.code(), response.code(), errorBody, response));
              return;
            }
            catch (IOException e) {
              future.completeExceptionally(new TrophyApiException("Network error executing HTTP request", e));
            }
          }

          @Override
          public void onFailure(@NotNull Call call, @NotNull IOException e) {
            future.completeExceptionally(new TrophyApiException("Network error executing HTTP request", e));
          }
        });
        return future;
      }
    }
