package so.trophy.resources.admin.points.boosts.types;

/**
 * This file was auto-generated by Fern from our API Definition.
 */


import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

public enum CreatePointsBoostsRequestBoostsItemRounding {
  DOWN("down"),

  UP("up"),

  NEAREST("nearest");

  private final String value;

  CreatePointsBoostsRequestBoostsItemRounding(String value) {
    this.value = value;
  }

  @JsonValue
  @java.lang.Override
  public String toString() {
    return this.value;
  }
}
