package so.trophy.resources.admin.points.boosts.requests;

/**
 * This file was auto-generated by Fern from our API Definition.
 */


import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import so.trophy.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;
import so.trophy.resources.admin.points.boosts.types.CreatePointsBoostsRequestBoostsItem;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreatePointsBoostsRequest.Builder.class
)
public final class CreatePointsBoostsRequest {
  private final String systemKey;

  private final List<CreatePointsBoostsRequestBoostsItem> boosts;

  private final Map<String, Object> additionalProperties;

  private CreatePointsBoostsRequest(String systemKey,
      List<CreatePointsBoostsRequestBoostsItem> boosts, Map<String, Object> additionalProperties) {
    this.systemKey = systemKey;
    this.boosts = boosts;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The key of the points system to create boosts for.
   */
  @JsonProperty("systemKey")
  public String getSystemKey() {
    return systemKey;
  }

  /**
   * @return Array of boosts to create. Maximum 1,000 boosts per request.
   */
  @JsonProperty("boosts")
  public List<CreatePointsBoostsRequestBoostsItem> getBoosts() {
    return boosts;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreatePointsBoostsRequest && equalTo((CreatePointsBoostsRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreatePointsBoostsRequest other) {
    return systemKey.equals(other.systemKey) && boosts.equals(other.boosts);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.systemKey, this.boosts);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static SystemKeyStage builder() {
    return new Builder();
  }

  public interface SystemKeyStage {
    /**
     * <p>The key of the points system to create boosts for.</p>
     */
    _FinalStage systemKey(@NotNull String systemKey);

    Builder from(CreatePointsBoostsRequest other);
  }

  public interface _FinalStage {
    CreatePointsBoostsRequest build();

    /**
     * <p>Array of boosts to create. Maximum 1,000 boosts per request.</p>
     */
    _FinalStage boosts(List<CreatePointsBoostsRequestBoostsItem> boosts);

    _FinalStage addBoosts(CreatePointsBoostsRequestBoostsItem boosts);

    _FinalStage addAllBoosts(List<CreatePointsBoostsRequestBoostsItem> boosts);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements SystemKeyStage, _FinalStage {
    private String systemKey;

    private List<CreatePointsBoostsRequestBoostsItem> boosts = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CreatePointsBoostsRequest other) {
      systemKey(other.getSystemKey());
      boosts(other.getBoosts());
      return this;
    }

    /**
     * <p>The key of the points system to create boosts for.</p>
     * <p>The key of the points system to create boosts for.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("systemKey")
    public _FinalStage systemKey(@NotNull String systemKey) {
      this.systemKey = Objects.requireNonNull(systemKey, "systemKey must not be null");
      return this;
    }

    /**
     * <p>Array of boosts to create. Maximum 1,000 boosts per request.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addAllBoosts(List<CreatePointsBoostsRequestBoostsItem> boosts) {
      if (boosts != null) {
        this.boosts.addAll(boosts);
      }
      return this;
    }

    /**
     * <p>Array of boosts to create. Maximum 1,000 boosts per request.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addBoosts(CreatePointsBoostsRequestBoostsItem boosts) {
      this.boosts.add(boosts);
      return this;
    }

    /**
     * <p>Array of boosts to create. Maximum 1,000 boosts per request.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "boosts",
        nulls = Nulls.SKIP
    )
    public _FinalStage boosts(List<CreatePointsBoostsRequestBoostsItem> boosts) {
      this.boosts.clear();
      this.boosts.addAll(boosts);
      return this;
    }

    @java.lang.Override
    public CreatePointsBoostsRequest build() {
      return new CreatePointsBoostsRequest(systemKey, boosts, additionalProperties);
    }
  }
}
