package so.trophy.resources.admin.streaks.freezes;

/**
 * This file was auto-generated by Fern from our API Definition.
 */


import so.trophy.core.ClientOptions;
import so.trophy.core.RequestOptions;
import java.util.concurrent.CompletableFuture;
import so.trophy.resources.admin.streaks.freezes.requests.CreateStreakFreezesRequest;
import so.trophy.types.CreateStreakFreezesResponse;

public class AsyncFreezesClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawFreezesClient rawClient;

  public AsyncFreezesClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawFreezesClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawFreezesClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Create streak freezes for multiple users.
   */
  public CompletableFuture<CreateStreakFreezesResponse> create(CreateStreakFreezesRequest request) {
    return this.rawClient.create(request).thenApply(response -> response.body());
  }

  /**
   * Create streak freezes for multiple users.
   */
  public CompletableFuture<CreateStreakFreezesResponse> create(CreateStreakFreezesRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.create(request, requestOptions).thenApply(response -> response.body());
  }
}
