package so.trophy.types;

/**
 * This file was auto-generated by Fern from our API Definition.
 */


import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import so.trophy.core.ObjectMappers;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = AdminLeaderboard.Builder.class
)
public final class AdminLeaderboard {
  private final String id;

  private final String name;

  private final String key;

  private final Optional<String> description;

  private final AdminLeaderboardStatus status;

  private final AdminLeaderboardRankBy rankBy;

  private final Optional<String> metricId;

  private final Optional<String> pointsSystemId;

  private final int maxParticipants;

  private final String start;

  private final Optional<String> end;

  private final List<String> breakdownAttributes;

  private final Optional<AdminLeaderboardRunUnit> runUnit;

  private final Optional<Integer> runInterval;

  private final Map<String, Object> additionalProperties;

  private AdminLeaderboard(String id, String name, String key, Optional<String> description,
      AdminLeaderboardStatus status, AdminLeaderboardRankBy rankBy, Optional<String> metricId,
      Optional<String> pointsSystemId, int maxParticipants, String start, Optional<String> end,
      List<String> breakdownAttributes, Optional<AdminLeaderboardRunUnit> runUnit,
      Optional<Integer> runInterval, Map<String, Object> additionalProperties) {
    this.id = id;
    this.name = name;
    this.key = key;
    this.description = description;
    this.status = status;
    this.rankBy = rankBy;
    this.metricId = metricId;
    this.pointsSystemId = pointsSystemId;
    this.maxParticipants = maxParticipants;
    this.start = start;
    this.end = end;
    this.breakdownAttributes = breakdownAttributes;
    this.runUnit = runUnit;
    this.runInterval = runInterval;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The UUID of the leaderboard.
   */
  @JsonProperty("id")
  public String getId() {
    return id;
  }

  /**
   * @return The leaderboard name.
   */
  @JsonProperty("name")
  public String getName() {
    return name;
  }

  /**
   * @return The leaderboard key.
   */
  @JsonProperty("key")
  public String getKey() {
    return key;
  }

  /**
   * @return The leaderboard description.
   */
  @JsonProperty("description")
  public Optional<String> getDescription() {
    return description;
  }

  /**
   * @return The current user-facing status of the leaderboard.
   */
  @JsonProperty("status")
  public AdminLeaderboardStatus getStatus() {
    return status;
  }

  /**
   * @return What the leaderboard ranks by.
   */
  @JsonProperty("rankBy")
  public AdminLeaderboardRankBy getRankBy() {
    return rankBy;
  }

  /**
   * @return The metric ID used when <code>rankBy</code> is <code>metric</code>.
   */
  @JsonProperty("metricId")
  public Optional<String> getMetricId() {
    return metricId;
  }

  /**
   * @return The points system ID used when <code>rankBy</code> is <code>points</code>.
   */
  @JsonProperty("pointsSystemId")
  public Optional<String> getPointsSystemId() {
    return pointsSystemId;
  }

  /**
   * @return The maximum number of participants.
   */
  @JsonProperty("maxParticipants")
  public int getMaxParticipants() {
    return maxParticipants;
  }

  /**
   * @return The leaderboard start date in YYYY-MM-DD format.
   */
  @JsonProperty("start")
  public String getStart() {
    return start;
  }

  /**
   * @return The optional leaderboard end date in YYYY-MM-DD format.
   */
  @JsonProperty("end")
  public Optional<String> getEnd() {
    return end;
  }

  /**
   * @return The UUIDs of the user attributes used for ranking breakdowns.
   */
  @JsonProperty("breakdownAttributes")
  public List<String> getBreakdownAttributes() {
    return breakdownAttributes;
  }

  /**
   * @return The recurrence unit when the leaderboard repeats.
   */
  @JsonProperty("runUnit")
  public Optional<AdminLeaderboardRunUnit> getRunUnit() {
    return runUnit;
  }

  /**
   * @return The number of recurrence units between leaderboard runs.
   */
  @JsonProperty("runInterval")
  public Optional<Integer> getRunInterval() {
    return runInterval;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof AdminLeaderboard && equalTo((AdminLeaderboard) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(AdminLeaderboard other) {
    return id.equals(other.id) && name.equals(other.name) && key.equals(other.key) && description.equals(other.description) && status.equals(other.status) && rankBy.equals(other.rankBy) && metricId.equals(other.metricId) && pointsSystemId.equals(other.pointsSystemId) && maxParticipants == other.maxParticipants && start.equals(other.start) && end.equals(other.end) && breakdownAttributes.equals(other.breakdownAttributes) && runUnit.equals(other.runUnit) && runInterval.equals(other.runInterval);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.name, this.key, this.description, this.status, this.rankBy, this.metricId, this.pointsSystemId, this.maxParticipants, this.start, this.end, this.breakdownAttributes, this.runUnit, this.runInterval);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static IdStage builder() {
    return new Builder();
  }

  public interface IdStage {
    /**
     * <p>The UUID of the leaderboard.</p>
     */
    NameStage id(@NotNull String id);

    Builder from(AdminLeaderboard other);
  }

  public interface NameStage {
    /**
     * <p>The leaderboard name.</p>
     */
    KeyStage name(@NotNull String name);
  }

  public interface KeyStage {
    /**
     * <p>The leaderboard key.</p>
     */
    StatusStage key(@NotNull String key);
  }

  public interface StatusStage {
    /**
     * <p>The current user-facing status of the leaderboard.</p>
     */
    RankByStage status(@NotNull AdminLeaderboardStatus status);
  }

  public interface RankByStage {
    /**
     * <p>What the leaderboard ranks by.</p>
     */
    MaxParticipantsStage rankBy(@NotNull AdminLeaderboardRankBy rankBy);
  }

  public interface MaxParticipantsStage {
    /**
     * <p>The maximum number of participants.</p>
     */
    StartStage maxParticipants(int maxParticipants);
  }

  public interface StartStage {
    /**
     * <p>The leaderboard start date in YYYY-MM-DD format.</p>
     */
    _FinalStage start(@NotNull String start);
  }

  public interface _FinalStage {
    AdminLeaderboard build();

    /**
     * <p>The leaderboard description.</p>
     */
    _FinalStage description(Optional<String> description);

    _FinalStage description(String description);

    /**
     * <p>The metric ID used when <code>rankBy</code> is <code>metric</code>.</p>
     */
    _FinalStage metricId(Optional<String> metricId);

    _FinalStage metricId(String metricId);

    /**
     * <p>The points system ID used when <code>rankBy</code> is <code>points</code>.</p>
     */
    _FinalStage pointsSystemId(Optional<String> pointsSystemId);

    _FinalStage pointsSystemId(String pointsSystemId);

    /**
     * <p>The optional leaderboard end date in YYYY-MM-DD format.</p>
     */
    _FinalStage end(Optional<String> end);

    _FinalStage end(String end);

    /**
     * <p>The UUIDs of the user attributes used for ranking breakdowns.</p>
     */
    _FinalStage breakdownAttributes(List<String> breakdownAttributes);

    _FinalStage addBreakdownAttributes(String breakdownAttributes);

    _FinalStage addAllBreakdownAttributes(List<String> breakdownAttributes);

    /**
     * <p>The recurrence unit when the leaderboard repeats.</p>
     */
    _FinalStage runUnit(Optional<AdminLeaderboardRunUnit> runUnit);

    _FinalStage runUnit(AdminLeaderboardRunUnit runUnit);

    /**
     * <p>The number of recurrence units between leaderboard runs.</p>
     */
    _FinalStage runInterval(Optional<Integer> runInterval);

    _FinalStage runInterval(Integer runInterval);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements IdStage, NameStage, KeyStage, StatusStage, RankByStage, MaxParticipantsStage, StartStage, _FinalStage {
    private String id;

    private String name;

    private String key;

    private AdminLeaderboardStatus status;

    private AdminLeaderboardRankBy rankBy;

    private int maxParticipants;

    private String start;

    private Optional<Integer> runInterval = Optional.empty();

    private Optional<AdminLeaderboardRunUnit> runUnit = Optional.empty();

    private List<String> breakdownAttributes = new ArrayList<>();

    private Optional<String> end = Optional.empty();

    private Optional<String> pointsSystemId = Optional.empty();

    private Optional<String> metricId = Optional.empty();

    private Optional<String> description = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(AdminLeaderboard other) {
      id(other.getId());
      name(other.getName());
      key(other.getKey());
      description(other.getDescription());
      status(other.getStatus());
      rankBy(other.getRankBy());
      metricId(other.getMetricId());
      pointsSystemId(other.getPointsSystemId());
      maxParticipants(other.getMaxParticipants());
      start(other.getStart());
      end(other.getEnd());
      breakdownAttributes(other.getBreakdownAttributes());
      runUnit(other.getRunUnit());
      runInterval(other.getRunInterval());
      return this;
    }

    /**
     * <p>The UUID of the leaderboard.</p>
     * <p>The UUID of the leaderboard.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("id")
    public NameStage id(@NotNull String id) {
      this.id = Objects.requireNonNull(id, "id must not be null");
      return this;
    }

    /**
     * <p>The leaderboard name.</p>
     * <p>The leaderboard name.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("name")
    public KeyStage name(@NotNull String name) {
      this.name = Objects.requireNonNull(name, "name must not be null");
      return this;
    }

    /**
     * <p>The leaderboard key.</p>
     * <p>The leaderboard key.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("key")
    public StatusStage key(@NotNull String key) {
      this.key = Objects.requireNonNull(key, "key must not be null");
      return this;
    }

    /**
     * <p>The current user-facing status of the leaderboard.</p>
     * <p>The current user-facing status of the leaderboard.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("status")
    public RankByStage status(@NotNull AdminLeaderboardStatus status) {
      this.status = Objects.requireNonNull(status, "status must not be null");
      return this;
    }

    /**
     * <p>What the leaderboard ranks by.</p>
     * <p>What the leaderboard ranks by.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("rankBy")
    public MaxParticipantsStage rankBy(@NotNull AdminLeaderboardRankBy rankBy) {
      this.rankBy = Objects.requireNonNull(rankBy, "rankBy must not be null");
      return this;
    }

    /**
     * <p>The maximum number of participants.</p>
     * <p>The maximum number of participants.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("maxParticipants")
    public StartStage maxParticipants(int maxParticipants) {
      this.maxParticipants = maxParticipants;
      return this;
    }

    /**
     * <p>The leaderboard start date in YYYY-MM-DD format.</p>
     * <p>The leaderboard start date in YYYY-MM-DD format.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("start")
    public _FinalStage start(@NotNull String start) {
      this.start = Objects.requireNonNull(start, "start must not be null");
      return this;
    }

    /**
     * <p>The number of recurrence units between leaderboard runs.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage runInterval(Integer runInterval) {
      this.runInterval = Optional.ofNullable(runInterval);
      return this;
    }

    /**
     * <p>The number of recurrence units between leaderboard runs.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "runInterval",
        nulls = Nulls.SKIP
    )
    public _FinalStage runInterval(Optional<Integer> runInterval) {
      this.runInterval = runInterval;
      return this;
    }

    /**
     * <p>The recurrence unit when the leaderboard repeats.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage runUnit(AdminLeaderboardRunUnit runUnit) {
      this.runUnit = Optional.ofNullable(runUnit);
      return this;
    }

    /**
     * <p>The recurrence unit when the leaderboard repeats.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "runUnit",
        nulls = Nulls.SKIP
    )
    public _FinalStage runUnit(Optional<AdminLeaderboardRunUnit> runUnit) {
      this.runUnit = runUnit;
      return this;
    }

    /**
     * <p>The UUIDs of the user attributes used for ranking breakdowns.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addAllBreakdownAttributes(List<String> breakdownAttributes) {
      if (breakdownAttributes != null) {
        this.breakdownAttributes.addAll(breakdownAttributes);
      }
      return this;
    }

    /**
     * <p>The UUIDs of the user attributes used for ranking breakdowns.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addBreakdownAttributes(String breakdownAttributes) {
      this.breakdownAttributes.add(breakdownAttributes);
      return this;
    }

    /**
     * <p>The UUIDs of the user attributes used for ranking breakdowns.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "breakdownAttributes",
        nulls = Nulls.SKIP
    )
    public _FinalStage breakdownAttributes(List<String> breakdownAttributes) {
      this.breakdownAttributes.clear();
      this.breakdownAttributes.addAll(breakdownAttributes);
      return this;
    }

    /**
     * <p>The optional leaderboard end date in YYYY-MM-DD format.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage end(String end) {
      this.end = Optional.ofNullable(end);
      return this;
    }

    /**
     * <p>The optional leaderboard end date in YYYY-MM-DD format.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "end",
        nulls = Nulls.SKIP
    )
    public _FinalStage end(Optional<String> end) {
      this.end = end;
      return this;
    }

    /**
     * <p>The points system ID used when <code>rankBy</code> is <code>points</code>.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage pointsSystemId(String pointsSystemId) {
      this.pointsSystemId = Optional.ofNullable(pointsSystemId);
      return this;
    }

    /**
     * <p>The points system ID used when <code>rankBy</code> is <code>points</code>.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "pointsSystemId",
        nulls = Nulls.SKIP
    )
    public _FinalStage pointsSystemId(Optional<String> pointsSystemId) {
      this.pointsSystemId = pointsSystemId;
      return this;
    }

    /**
     * <p>The metric ID used when <code>rankBy</code> is <code>metric</code>.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage metricId(String metricId) {
      this.metricId = Optional.ofNullable(metricId);
      return this;
    }

    /**
     * <p>The metric ID used when <code>rankBy</code> is <code>metric</code>.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "metricId",
        nulls = Nulls.SKIP
    )
    public _FinalStage metricId(Optional<String> metricId) {
      this.metricId = metricId;
      return this;
    }

    /**
     * <p>The leaderboard description.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage description(String description) {
      this.description = Optional.ofNullable(description);
      return this;
    }

    /**
     * <p>The leaderboard description.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "description",
        nulls = Nulls.SKIP
    )
    public _FinalStage description(Optional<String> description) {
      this.description = description;
      return this;
    }

    @java.lang.Override
    public AdminLeaderboard build() {
      return new AdminLeaderboard(id, name, key, description, status, rankBy, metricId, pointsSystemId, maxParticipants, start, end, breakdownAttributes, runUnit, runInterval, additionalProperties);
    }
  }
}
