package so.trophy.types;

/**
 * This file was auto-generated by Fern from our API Definition.
 */


import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import so.trophy.core.ObjectMappers;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreatePointsSystemRequestItem.Builder.class
)
public final class CreatePointsSystemRequestItem {
  private final String name;

  private final String key;

  private final Optional<String> description;

  private final Optional<CreatePointsSystemRequestItemBadge> badge;

  private final Optional<Integer> maxPoints;

  private final Optional<List<CreatePointsLevelRequestItem>> levels;

  private final Optional<List<CreatePointsBoostRequestItem>> boosts;

  private final Optional<List<CreatePointsTriggerRequestItem>> triggers;

  private final Map<String, Object> additionalProperties;

  private CreatePointsSystemRequestItem(String name, String key, Optional<String> description,
      Optional<CreatePointsSystemRequestItemBadge> badge, Optional<Integer> maxPoints,
      Optional<List<CreatePointsLevelRequestItem>> levels,
      Optional<List<CreatePointsBoostRequestItem>> boosts,
      Optional<List<CreatePointsTriggerRequestItem>> triggers,
      Map<String, Object> additionalProperties) {
    this.name = name;
    this.key = key;
    this.description = description;
    this.badge = badge;
    this.maxPoints = maxPoints;
    this.levels = levels;
    this.boosts = boosts;
    this.triggers = triggers;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The points system name.
   */
  @JsonProperty("name")
  public String getName() {
    return name;
  }

  /**
   * @return The points system key. Only alphanumeric characters, hyphens, and underscores are permitted.
   */
  @JsonProperty("key")
  public String getKey() {
    return key;
  }

  /**
   * @return A short description of the points system.
   */
  @JsonProperty("description")
  public Optional<String> getDescription() {
    return description;
  }

  /**
   * @return An optional badge for the points system.
   */
  @JsonProperty("badge")
  public Optional<CreatePointsSystemRequestItemBadge> getBadge() {
    return badge;
  }

  /**
   * @return Optional maximum points a user can earn.
   */
  @JsonProperty("maxPoints")
  public Optional<Integer> getMaxPoints() {
    return maxPoints;
  }

  /**
   * @return Optional array of levels to create alongside the system.
   */
  @JsonProperty("levels")
  public Optional<List<CreatePointsLevelRequestItem>> getLevels() {
    return levels;
  }

  /**
   * @return Optional array of boosts to create alongside the system.
   */
  @JsonProperty("boosts")
  public Optional<List<CreatePointsBoostRequestItem>> getBoosts() {
    return boosts;
  }

  /**
   * @return Optional array of triggers to create alongside the system.
   */
  @JsonProperty("triggers")
  public Optional<List<CreatePointsTriggerRequestItem>> getTriggers() {
    return triggers;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreatePointsSystemRequestItem && equalTo((CreatePointsSystemRequestItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreatePointsSystemRequestItem other) {
    return name.equals(other.name) && key.equals(other.key) && description.equals(other.description) && badge.equals(other.badge) && maxPoints.equals(other.maxPoints) && levels.equals(other.levels) && boosts.equals(other.boosts) && triggers.equals(other.triggers);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.name, this.key, this.description, this.badge, this.maxPoints, this.levels, this.boosts, this.triggers);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static NameStage builder() {
    return new Builder();
  }

  public interface NameStage {
    /**
     * <p>The points system name.</p>
     */
    KeyStage name(@NotNull String name);

    Builder from(CreatePointsSystemRequestItem other);
  }

  public interface KeyStage {
    /**
     * <p>The points system key. Only alphanumeric characters, hyphens, and underscores are permitted.</p>
     */
    _FinalStage key(@NotNull String key);
  }

  public interface _FinalStage {
    CreatePointsSystemRequestItem build();

    /**
     * <p>A short description of the points system.</p>
     */
    _FinalStage description(Optional<String> description);

    _FinalStage description(String description);

    /**
     * <p>An optional badge for the points system.</p>
     */
    _FinalStage badge(Optional<CreatePointsSystemRequestItemBadge> badge);

    _FinalStage badge(CreatePointsSystemRequestItemBadge badge);

    /**
     * <p>Optional maximum points a user can earn.</p>
     */
    _FinalStage maxPoints(Optional<Integer> maxPoints);

    _FinalStage maxPoints(Integer maxPoints);

    /**
     * <p>Optional array of levels to create alongside the system.</p>
     */
    _FinalStage levels(Optional<List<CreatePointsLevelRequestItem>> levels);

    _FinalStage levels(List<CreatePointsLevelRequestItem> levels);

    /**
     * <p>Optional array of boosts to create alongside the system.</p>
     */
    _FinalStage boosts(Optional<List<CreatePointsBoostRequestItem>> boosts);

    _FinalStage boosts(List<CreatePointsBoostRequestItem> boosts);

    /**
     * <p>Optional array of triggers to create alongside the system.</p>
     */
    _FinalStage triggers(Optional<List<CreatePointsTriggerRequestItem>> triggers);

    _FinalStage triggers(List<CreatePointsTriggerRequestItem> triggers);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements NameStage, KeyStage, _FinalStage {
    private String name;

    private String key;

    private Optional<List<CreatePointsTriggerRequestItem>> triggers = Optional.empty();

    private Optional<List<CreatePointsBoostRequestItem>> boosts = Optional.empty();

    private Optional<List<CreatePointsLevelRequestItem>> levels = Optional.empty();

    private Optional<Integer> maxPoints = Optional.empty();

    private Optional<CreatePointsSystemRequestItemBadge> badge = Optional.empty();

    private Optional<String> description = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CreatePointsSystemRequestItem other) {
      name(other.getName());
      key(other.getKey());
      description(other.getDescription());
      badge(other.getBadge());
      maxPoints(other.getMaxPoints());
      levels(other.getLevels());
      boosts(other.getBoosts());
      triggers(other.getTriggers());
      return this;
    }

    /**
     * <p>The points system name.</p>
     * <p>The points system name.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("name")
    public KeyStage name(@NotNull String name) {
      this.name = Objects.requireNonNull(name, "name must not be null");
      return this;
    }

    /**
     * <p>The points system key. Only alphanumeric characters, hyphens, and underscores are permitted.</p>
     * <p>The points system key. Only alphanumeric characters, hyphens, and underscores are permitted.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("key")
    public _FinalStage key(@NotNull String key) {
      this.key = Objects.requireNonNull(key, "key must not be null");
      return this;
    }

    /**
     * <p>Optional array of triggers to create alongside the system.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage triggers(List<CreatePointsTriggerRequestItem> triggers) {
      this.triggers = Optional.ofNullable(triggers);
      return this;
    }

    /**
     * <p>Optional array of triggers to create alongside the system.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "triggers",
        nulls = Nulls.SKIP
    )
    public _FinalStage triggers(Optional<List<CreatePointsTriggerRequestItem>> triggers) {
      this.triggers = triggers;
      return this;
    }

    /**
     * <p>Optional array of boosts to create alongside the system.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage boosts(List<CreatePointsBoostRequestItem> boosts) {
      this.boosts = Optional.ofNullable(boosts);
      return this;
    }

    /**
     * <p>Optional array of boosts to create alongside the system.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "boosts",
        nulls = Nulls.SKIP
    )
    public _FinalStage boosts(Optional<List<CreatePointsBoostRequestItem>> boosts) {
      this.boosts = boosts;
      return this;
    }

    /**
     * <p>Optional array of levels to create alongside the system.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage levels(List<CreatePointsLevelRequestItem> levels) {
      this.levels = Optional.ofNullable(levels);
      return this;
    }

    /**
     * <p>Optional array of levels to create alongside the system.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "levels",
        nulls = Nulls.SKIP
    )
    public _FinalStage levels(Optional<List<CreatePointsLevelRequestItem>> levels) {
      this.levels = levels;
      return this;
    }

    /**
     * <p>Optional maximum points a user can earn.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage maxPoints(Integer maxPoints) {
      this.maxPoints = Optional.ofNullable(maxPoints);
      return this;
    }

    /**
     * <p>Optional maximum points a user can earn.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "maxPoints",
        nulls = Nulls.SKIP
    )
    public _FinalStage maxPoints(Optional<Integer> maxPoints) {
      this.maxPoints = maxPoints;
      return this;
    }

    /**
     * <p>An optional badge for the points system.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage badge(CreatePointsSystemRequestItemBadge badge) {
      this.badge = Optional.ofNullable(badge);
      return this;
    }

    /**
     * <p>An optional badge for the points system.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "badge",
        nulls = Nulls.SKIP
    )
    public _FinalStage badge(Optional<CreatePointsSystemRequestItemBadge> badge) {
      this.badge = badge;
      return this;
    }

    /**
     * <p>A short description of the points system.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage description(String description) {
      this.description = Optional.ofNullable(description);
      return this;
    }

    /**
     * <p>A short description of the points system.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "description",
        nulls = Nulls.SKIP
    )
    public _FinalStage description(Optional<String> description) {
      this.description = description;
      return this;
    }

    @java.lang.Override
    public CreatePointsSystemRequestItem build() {
      return new CreatePointsSystemRequestItem(name, key, description, badge, maxPoints, levels, boosts, triggers, additionalProperties);
    }
  }
}
