package so.trophy.types;

/**
 * This file was auto-generated by Fern from our API Definition.
 */


import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

public enum CreatedPointsBoostStatus {
  ACTIVE("active"),

  SCHEDULED("scheduled"),

  FINISHED("finished");

  private final String value;

  CreatedPointsBoostStatus(String value) {
    this.value = value;
  }

  @JsonValue
  @java.lang.Override
  public String toString() {
    return this.value;
  }
}
