package so.trophy.types;

/**
 * This file was auto-generated by Fern from our API Definition.
 */


import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import so.trophy.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreatePointsBoostRequestItem.Builder.class
)
public final class CreatePointsBoostRequestItem {
  private final Optional<String> userId;

  private final String name;

  private final String start;

  private final Optional<String> end;

  private final double multiplier;

  private final Optional<CreatePointsBoostRequestItemRounding> rounding;

  private final Optional<List<CreatePointsBoostRequestItemUserAttributesItem>> userAttributes;

  private final Map<String, Object> additionalProperties;

  private CreatePointsBoostRequestItem(Optional<String> userId, String name, String start,
      Optional<String> end, double multiplier,
      Optional<CreatePointsBoostRequestItemRounding> rounding,
      Optional<List<CreatePointsBoostRequestItemUserAttributesItem>> userAttributes,
      Map<String, Object> additionalProperties) {
    this.userId = userId;
    this.name = name;
    this.start = start;
    this.end = end;
    this.multiplier = multiplier;
    this.rounding = rounding;
    this.userAttributes = userAttributes;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The ID of the user to create a boost for. Mutually exclusive with <code>userAttributes</code> — providing <code>userAttributes</code> when <code>userId</code> is set will result in an error. Omit for a global boost.
   */
  @JsonProperty("userId")
  public Optional<String> getUserId() {
    return userId;
  }

  /**
   * @return The name of the boost.
   */
  @JsonProperty("name")
  public String getName() {
    return name;
  }

  /**
   * @return The start date of the boost (YYYY-MM-DD).
   */
  @JsonProperty("start")
  public String getStart() {
    return start;
  }

  /**
   * @return The end date of the boost (YYYY-MM-DD). If null, the boost has no end date.
   */
  @JsonProperty("end")
  public Optional<String> getEnd() {
    return end;
  }

  /**
   * @return The points multiplier. Must be greater than 0, not equal to 1, and less than 100.
   */
  @JsonProperty("multiplier")
  public double getMultiplier() {
    return multiplier;
  }

  /**
   * @return How to round the boosted points. Defaults to 'down'.
   */
  @JsonProperty("rounding")
  public Optional<CreatePointsBoostRequestItemRounding> getRounding() {
    return rounding;
  }

  /**
   * @return User attribute filters for the boost. Cannot be provided when <code>userId</code> is set.
   */
  @JsonProperty("userAttributes")
  public Optional<List<CreatePointsBoostRequestItemUserAttributesItem>> getUserAttributes() {
    return userAttributes;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreatePointsBoostRequestItem && equalTo((CreatePointsBoostRequestItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreatePointsBoostRequestItem other) {
    return userId.equals(other.userId) && name.equals(other.name) && start.equals(other.start) && end.equals(other.end) && multiplier == other.multiplier && rounding.equals(other.rounding) && userAttributes.equals(other.userAttributes);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.userId, this.name, this.start, this.end, this.multiplier, this.rounding, this.userAttributes);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static NameStage builder() {
    return new Builder();
  }

  public interface NameStage {
    /**
     * <p>The name of the boost.</p>
     */
    StartStage name(@NotNull String name);

    Builder from(CreatePointsBoostRequestItem other);
  }

  public interface StartStage {
    /**
     * <p>The start date of the boost (YYYY-MM-DD).</p>
     */
    MultiplierStage start(@NotNull String start);
  }

  public interface MultiplierStage {
    /**
     * <p>The points multiplier. Must be greater than 0, not equal to 1, and less than 100.</p>
     */
    _FinalStage multiplier(double multiplier);
  }

  public interface _FinalStage {
    CreatePointsBoostRequestItem build();

    /**
     * <p>The ID of the user to create a boost for. Mutually exclusive with <code>userAttributes</code> — providing <code>userAttributes</code> when <code>userId</code> is set will result in an error. Omit for a global boost.</p>
     */
    _FinalStage userId(Optional<String> userId);

    _FinalStage userId(String userId);

    /**
     * <p>The end date of the boost (YYYY-MM-DD). If null, the boost has no end date.</p>
     */
    _FinalStage end(Optional<String> end);

    _FinalStage end(String end);

    /**
     * <p>How to round the boosted points. Defaults to 'down'.</p>
     */
    _FinalStage rounding(Optional<CreatePointsBoostRequestItemRounding> rounding);

    _FinalStage rounding(CreatePointsBoostRequestItemRounding rounding);

    /**
     * <p>User attribute filters for the boost. Cannot be provided when <code>userId</code> is set.</p>
     */
    _FinalStage userAttributes(
        Optional<List<CreatePointsBoostRequestItemUserAttributesItem>> userAttributes);

    _FinalStage userAttributes(List<CreatePointsBoostRequestItemUserAttributesItem> userAttributes);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements NameStage, StartStage, MultiplierStage, _FinalStage {
    private String name;

    private String start;

    private double multiplier;

    private Optional<List<CreatePointsBoostRequestItemUserAttributesItem>> userAttributes = Optional.empty();

    private Optional<CreatePointsBoostRequestItemRounding> rounding = Optional.empty();

    private Optional<String> end = Optional.empty();

    private Optional<String> userId = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CreatePointsBoostRequestItem other) {
      userId(other.getUserId());
      name(other.getName());
      start(other.getStart());
      end(other.getEnd());
      multiplier(other.getMultiplier());
      rounding(other.getRounding());
      userAttributes(other.getUserAttributes());
      return this;
    }

    /**
     * <p>The name of the boost.</p>
     * <p>The name of the boost.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("name")
    public StartStage name(@NotNull String name) {
      this.name = Objects.requireNonNull(name, "name must not be null");
      return this;
    }

    /**
     * <p>The start date of the boost (YYYY-MM-DD).</p>
     * <p>The start date of the boost (YYYY-MM-DD).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("start")
    public MultiplierStage start(@NotNull String start) {
      this.start = Objects.requireNonNull(start, "start must not be null");
      return this;
    }

    /**
     * <p>The points multiplier. Must be greater than 0, not equal to 1, and less than 100.</p>
     * <p>The points multiplier. Must be greater than 0, not equal to 1, and less than 100.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("multiplier")
    public _FinalStage multiplier(double multiplier) {
      this.multiplier = multiplier;
      return this;
    }

    /**
     * <p>User attribute filters for the boost. Cannot be provided when <code>userId</code> is set.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage userAttributes(
        List<CreatePointsBoostRequestItemUserAttributesItem> userAttributes) {
      this.userAttributes = Optional.ofNullable(userAttributes);
      return this;
    }

    /**
     * <p>User attribute filters for the boost. Cannot be provided when <code>userId</code> is set.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "userAttributes",
        nulls = Nulls.SKIP
    )
    public _FinalStage userAttributes(
        Optional<List<CreatePointsBoostRequestItemUserAttributesItem>> userAttributes) {
      this.userAttributes = userAttributes;
      return this;
    }

    /**
     * <p>How to round the boosted points. Defaults to 'down'.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage rounding(CreatePointsBoostRequestItemRounding rounding) {
      this.rounding = Optional.ofNullable(rounding);
      return this;
    }

    /**
     * <p>How to round the boosted points. Defaults to 'down'.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "rounding",
        nulls = Nulls.SKIP
    )
    public _FinalStage rounding(Optional<CreatePointsBoostRequestItemRounding> rounding) {
      this.rounding = rounding;
      return this;
    }

    /**
     * <p>The end date of the boost (YYYY-MM-DD). If null, the boost has no end date.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage end(String end) {
      this.end = Optional.ofNullable(end);
      return this;
    }

    /**
     * <p>The end date of the boost (YYYY-MM-DD). If null, the boost has no end date.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "end",
        nulls = Nulls.SKIP
    )
    public _FinalStage end(Optional<String> end) {
      this.end = end;
      return this;
    }

    /**
     * <p>The ID of the user to create a boost for. Mutually exclusive with <code>userAttributes</code> — providing <code>userAttributes</code> when <code>userId</code> is set will result in an error. Omit for a global boost.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage userId(String userId) {
      this.userId = Optional.ofNullable(userId);
      return this;
    }

    /**
     * <p>The ID of the user to create a boost for. Mutually exclusive with <code>userAttributes</code> — providing <code>userAttributes</code> when <code>userId</code> is set will result in an error. Omit for a global boost.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "userId",
        nulls = Nulls.SKIP
    )
    public _FinalStage userId(Optional<String> userId) {
      this.userId = userId;
      return this;
    }

    @java.lang.Override
    public CreatePointsBoostRequestItem build() {
      return new CreatePointsBoostRequestItem(userId, name, start, end, multiplier, rounding, userAttributes, additionalProperties);
    }
  }
}
