package so.trophy.types;

/**
 * This file was auto-generated by Fern from our API Definition.
 */


import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import so.trophy.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreateLeaderboardsResponse.Builder.class
)
public final class CreateLeaderboardsResponse {
  private final List<AdminLeaderboard> created;

  private final List<AdminIssue> issues;

  private final Map<String, Object> additionalProperties;

  private CreateLeaderboardsResponse(List<AdminLeaderboard> created, List<AdminIssue> issues,
      Map<String, Object> additionalProperties) {
    this.created = created;
    this.issues = issues;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Array of successfully created leaderboards.
   */
  @JsonProperty("created")
  public List<AdminLeaderboard> getCreated() {
    return created;
  }

  /**
   * @return Array of issues encountered during leaderboard creation.
   */
  @JsonProperty("issues")
  public List<AdminIssue> getIssues() {
    return issues;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreateLeaderboardsResponse && equalTo((CreateLeaderboardsResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreateLeaderboardsResponse other) {
    return created.equals(other.created) && issues.equals(other.issues);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.created, this.issues);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private List<AdminLeaderboard> created = new ArrayList<>();

    private List<AdminIssue> issues = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(CreateLeaderboardsResponse other) {
      created(other.getCreated());
      issues(other.getIssues());
      return this;
    }

    /**
     * <p>Array of successfully created leaderboards.</p>
     */
    @JsonSetter(
        value = "created",
        nulls = Nulls.SKIP
    )
    public Builder created(List<AdminLeaderboard> created) {
      this.created.clear();
      this.created.addAll(created);
      return this;
    }

    public Builder addCreated(AdminLeaderboard created) {
      this.created.add(created);
      return this;
    }

    public Builder addAllCreated(List<AdminLeaderboard> created) {
      if (created != null) {
        this.created.addAll(created);
      }
      return this;
    }

    /**
     * <p>Array of issues encountered during leaderboard creation.</p>
     */
    @JsonSetter(
        value = "issues",
        nulls = Nulls.SKIP
    )
    public Builder issues(List<AdminIssue> issues) {
      this.issues.clear();
      this.issues.addAll(issues);
      return this;
    }

    public Builder addIssues(AdminIssue issues) {
      this.issues.add(issues);
      return this;
    }

    public Builder addAllIssues(List<AdminIssue> issues) {
      if (issues != null) {
        this.issues.addAll(issues);
      }
      return this;
    }

    public CreateLeaderboardsResponse build() {
      return new CreateLeaderboardsResponse(created, issues, additionalProperties);
    }
  }
}
