package so.trophy.types;

/**
 * This file was auto-generated by Fern from our API Definition.
 */


import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import so.trophy.core.ObjectMappers;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreatePointsTriggerRequestItem.Builder.class
)
public final class CreatePointsTriggerRequestItem {
  private final CreatePointsTriggerRequestItemType type;

  private final int points;

  private final Optional<CreatePointsTriggerRequestItemStatus> status;

  private final Optional<List<CreatePointsTriggerRequestItemUserAttributesItem>> userAttributes;

  private final Optional<String> metricId;

  private final Optional<Integer> metricThreshold;

  private final Optional<List<CreatePointsTriggerRequestItemEventAttributesItem>> eventAttributes;

  private final Optional<String> achievementId;

  private final Optional<Integer> streakLength;

  private final Optional<CreatePointsTriggerRequestItemTimeUnit> timeUnit;

  private final Optional<Integer> timeInterval;

  private final Optional<Boolean> blockIfOutOfPoints;

  private final Map<String, Object> additionalProperties;

  private CreatePointsTriggerRequestItem(CreatePointsTriggerRequestItemType type, int points,
      Optional<CreatePointsTriggerRequestItemStatus> status,
      Optional<List<CreatePointsTriggerRequestItemUserAttributesItem>> userAttributes,
      Optional<String> metricId, Optional<Integer> metricThreshold,
      Optional<List<CreatePointsTriggerRequestItemEventAttributesItem>> eventAttributes,
      Optional<String> achievementId, Optional<Integer> streakLength,
      Optional<CreatePointsTriggerRequestItemTimeUnit> timeUnit, Optional<Integer> timeInterval,
      Optional<Boolean> blockIfOutOfPoints, Map<String, Object> additionalProperties) {
    this.type = type;
    this.points = points;
    this.status = status;
    this.userAttributes = userAttributes;
    this.metricId = metricId;
    this.metricThreshold = metricThreshold;
    this.eventAttributes = eventAttributes;
    this.achievementId = achievementId;
    this.streakLength = streakLength;
    this.timeUnit = timeUnit;
    this.timeInterval = timeInterval;
    this.blockIfOutOfPoints = blockIfOutOfPoints;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The type of trigger.
   */
  @JsonProperty("type")
  public CreatePointsTriggerRequestItemType getType() {
    return type;
  }

  /**
   * @return The number of points to award or deduct when the trigger fires. Cannot be zero.
   */
  @JsonProperty("points")
  public int getPoints() {
    return points;
  }

  /**
   * @return The status of the trigger. Defaults to 'inactive'.
   */
  @JsonProperty("status")
  public Optional<CreatePointsTriggerRequestItemStatus> getStatus() {
    return status;
  }

  /**
   * @return Optional user attribute filters for the trigger.
   */
  @JsonProperty("userAttributes")
  public Optional<List<CreatePointsTriggerRequestItemUserAttributesItem>> getUserAttributes() {
    return userAttributes;
  }

  /**
   * @return Required if type is <code>metric</code>. The UUID of the metric.
   */
  @JsonProperty("metricId")
  public Optional<String> getMetricId() {
    return metricId;
  }

  /**
   * @return Required if type is <code>metric</code>. The metric increment that triggers the points.
   */
  @JsonProperty("metricThreshold")
  public Optional<Integer> getMetricThreshold() {
    return metricThreshold;
  }

  /**
   * @return Optional event attribute filters. Only permitted if type is <code>metric</code>.
   */
  @JsonProperty("eventAttributes")
  public Optional<List<CreatePointsTriggerRequestItemEventAttributesItem>> getEventAttributes() {
    return eventAttributes;
  }

  /**
   * @return Required if type is <code>achievement</code>. The UUID of the achievement.
   */
  @JsonProperty("achievementId")
  public Optional<String> getAchievementId() {
    return achievementId;
  }

  /**
   * @return Required if type is <code>streak</code>. The number of streak periods that triggers the points.
   */
  @JsonProperty("streakLength")
  public Optional<Integer> getStreakLength() {
    return streakLength;
  }

  /**
   * @return Required if type is <code>time</code>. The unit for the time interval.
   */
  @JsonProperty("timeUnit")
  public Optional<CreatePointsTriggerRequestItemTimeUnit> getTimeUnit() {
    return timeUnit;
  }

  /**
   * @return Required if type is <code>time</code>. The number of time units between recurring awards.
   */
  @JsonProperty("timeInterval")
  public Optional<Integer> getTimeInterval() {
    return timeInterval;
  }

  /**
   * @return Whether to block metric events that would reduce the user's points below zero. Defaults to false.
   */
  @JsonProperty("blockIfOutOfPoints")
  public Optional<Boolean> getBlockIfOutOfPoints() {
    return blockIfOutOfPoints;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreatePointsTriggerRequestItem && equalTo((CreatePointsTriggerRequestItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreatePointsTriggerRequestItem other) {
    return type.equals(other.type) && points == other.points && status.equals(other.status) && userAttributes.equals(other.userAttributes) && metricId.equals(other.metricId) && metricThreshold.equals(other.metricThreshold) && eventAttributes.equals(other.eventAttributes) && achievementId.equals(other.achievementId) && streakLength.equals(other.streakLength) && timeUnit.equals(other.timeUnit) && timeInterval.equals(other.timeInterval) && blockIfOutOfPoints.equals(other.blockIfOutOfPoints);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.type, this.points, this.status, this.userAttributes, this.metricId, this.metricThreshold, this.eventAttributes, this.achievementId, this.streakLength, this.timeUnit, this.timeInterval, this.blockIfOutOfPoints);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static TypeStage builder() {
    return new Builder();
  }

  public interface TypeStage {
    /**
     * <p>The type of trigger.</p>
     */
    PointsStage type(@NotNull CreatePointsTriggerRequestItemType type);

    Builder from(CreatePointsTriggerRequestItem other);
  }

  public interface PointsStage {
    /**
     * <p>The number of points to award or deduct when the trigger fires. Cannot be zero.</p>
     */
    _FinalStage points(int points);
  }

  public interface _FinalStage {
    CreatePointsTriggerRequestItem build();

    /**
     * <p>The status of the trigger. Defaults to 'inactive'.</p>
     */
    _FinalStage status(Optional<CreatePointsTriggerRequestItemStatus> status);

    _FinalStage status(CreatePointsTriggerRequestItemStatus status);

    /**
     * <p>Optional user attribute filters for the trigger.</p>
     */
    _FinalStage userAttributes(
        Optional<List<CreatePointsTriggerRequestItemUserAttributesItem>> userAttributes);

    _FinalStage userAttributes(
        List<CreatePointsTriggerRequestItemUserAttributesItem> userAttributes);

    /**
     * <p>Required if type is <code>metric</code>. The UUID of the metric.</p>
     */
    _FinalStage metricId(Optional<String> metricId);

    _FinalStage metricId(String metricId);

    /**
     * <p>Required if type is <code>metric</code>. The metric increment that triggers the points.</p>
     */
    _FinalStage metricThreshold(Optional<Integer> metricThreshold);

    _FinalStage metricThreshold(Integer metricThreshold);

    /**
     * <p>Optional event attribute filters. Only permitted if type is <code>metric</code>.</p>
     */
    _FinalStage eventAttributes(
        Optional<List<CreatePointsTriggerRequestItemEventAttributesItem>> eventAttributes);

    _FinalStage eventAttributes(
        List<CreatePointsTriggerRequestItemEventAttributesItem> eventAttributes);

    /**
     * <p>Required if type is <code>achievement</code>. The UUID of the achievement.</p>
     */
    _FinalStage achievementId(Optional<String> achievementId);

    _FinalStage achievementId(String achievementId);

    /**
     * <p>Required if type is <code>streak</code>. The number of streak periods that triggers the points.</p>
     */
    _FinalStage streakLength(Optional<Integer> streakLength);

    _FinalStage streakLength(Integer streakLength);

    /**
     * <p>Required if type is <code>time</code>. The unit for the time interval.</p>
     */
    _FinalStage timeUnit(Optional<CreatePointsTriggerRequestItemTimeUnit> timeUnit);

    _FinalStage timeUnit(CreatePointsTriggerRequestItemTimeUnit timeUnit);

    /**
     * <p>Required if type is <code>time</code>. The number of time units between recurring awards.</p>
     */
    _FinalStage timeInterval(Optional<Integer> timeInterval);

    _FinalStage timeInterval(Integer timeInterval);

    /**
     * <p>Whether to block metric events that would reduce the user's points below zero. Defaults to false.</p>
     */
    _FinalStage blockIfOutOfPoints(Optional<Boolean> blockIfOutOfPoints);

    _FinalStage blockIfOutOfPoints(Boolean blockIfOutOfPoints);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements TypeStage, PointsStage, _FinalStage {
    private CreatePointsTriggerRequestItemType type;

    private int points;

    private Optional<Boolean> blockIfOutOfPoints = Optional.empty();

    private Optional<Integer> timeInterval = Optional.empty();

    private Optional<CreatePointsTriggerRequestItemTimeUnit> timeUnit = Optional.empty();

    private Optional<Integer> streakLength = Optional.empty();

    private Optional<String> achievementId = Optional.empty();

    private Optional<List<CreatePointsTriggerRequestItemEventAttributesItem>> eventAttributes = Optional.empty();

    private Optional<Integer> metricThreshold = Optional.empty();

    private Optional<String> metricId = Optional.empty();

    private Optional<List<CreatePointsTriggerRequestItemUserAttributesItem>> userAttributes = Optional.empty();

    private Optional<CreatePointsTriggerRequestItemStatus> status = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CreatePointsTriggerRequestItem other) {
      type(other.getType());
      points(other.getPoints());
      status(other.getStatus());
      userAttributes(other.getUserAttributes());
      metricId(other.getMetricId());
      metricThreshold(other.getMetricThreshold());
      eventAttributes(other.getEventAttributes());
      achievementId(other.getAchievementId());
      streakLength(other.getStreakLength());
      timeUnit(other.getTimeUnit());
      timeInterval(other.getTimeInterval());
      blockIfOutOfPoints(other.getBlockIfOutOfPoints());
      return this;
    }

    /**
     * <p>The type of trigger.</p>
     * <p>The type of trigger.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("type")
    public PointsStage type(@NotNull CreatePointsTriggerRequestItemType type) {
      this.type = Objects.requireNonNull(type, "type must not be null");
      return this;
    }

    /**
     * <p>The number of points to award or deduct when the trigger fires. Cannot be zero.</p>
     * <p>The number of points to award or deduct when the trigger fires. Cannot be zero.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("points")
    public _FinalStage points(int points) {
      this.points = points;
      return this;
    }

    /**
     * <p>Whether to block metric events that would reduce the user's points below zero. Defaults to false.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage blockIfOutOfPoints(Boolean blockIfOutOfPoints) {
      this.blockIfOutOfPoints = Optional.ofNullable(blockIfOutOfPoints);
      return this;
    }

    /**
     * <p>Whether to block metric events that would reduce the user's points below zero. Defaults to false.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "blockIfOutOfPoints",
        nulls = Nulls.SKIP
    )
    public _FinalStage blockIfOutOfPoints(Optional<Boolean> blockIfOutOfPoints) {
      this.blockIfOutOfPoints = blockIfOutOfPoints;
      return this;
    }

    /**
     * <p>Required if type is <code>time</code>. The number of time units between recurring awards.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage timeInterval(Integer timeInterval) {
      this.timeInterval = Optional.ofNullable(timeInterval);
      return this;
    }

    /**
     * <p>Required if type is <code>time</code>. The number of time units between recurring awards.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "timeInterval",
        nulls = Nulls.SKIP
    )
    public _FinalStage timeInterval(Optional<Integer> timeInterval) {
      this.timeInterval = timeInterval;
      return this;
    }

    /**
     * <p>Required if type is <code>time</code>. The unit for the time interval.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage timeUnit(CreatePointsTriggerRequestItemTimeUnit timeUnit) {
      this.timeUnit = Optional.ofNullable(timeUnit);
      return this;
    }

    /**
     * <p>Required if type is <code>time</code>. The unit for the time interval.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "timeUnit",
        nulls = Nulls.SKIP
    )
    public _FinalStage timeUnit(Optional<CreatePointsTriggerRequestItemTimeUnit> timeUnit) {
      this.timeUnit = timeUnit;
      return this;
    }

    /**
     * <p>Required if type is <code>streak</code>. The number of streak periods that triggers the points.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage streakLength(Integer streakLength) {
      this.streakLength = Optional.ofNullable(streakLength);
      return this;
    }

    /**
     * <p>Required if type is <code>streak</code>. The number of streak periods that triggers the points.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "streakLength",
        nulls = Nulls.SKIP
    )
    public _FinalStage streakLength(Optional<Integer> streakLength) {
      this.streakLength = streakLength;
      return this;
    }

    /**
     * <p>Required if type is <code>achievement</code>. The UUID of the achievement.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage achievementId(String achievementId) {
      this.achievementId = Optional.ofNullable(achievementId);
      return this;
    }

    /**
     * <p>Required if type is <code>achievement</code>. The UUID of the achievement.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "achievementId",
        nulls = Nulls.SKIP
    )
    public _FinalStage achievementId(Optional<String> achievementId) {
      this.achievementId = achievementId;
      return this;
    }

    /**
     * <p>Optional event attribute filters. Only permitted if type is <code>metric</code>.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage eventAttributes(
        List<CreatePointsTriggerRequestItemEventAttributesItem> eventAttributes) {
      this.eventAttributes = Optional.ofNullable(eventAttributes);
      return this;
    }

    /**
     * <p>Optional event attribute filters. Only permitted if type is <code>metric</code>.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "eventAttributes",
        nulls = Nulls.SKIP
    )
    public _FinalStage eventAttributes(
        Optional<List<CreatePointsTriggerRequestItemEventAttributesItem>> eventAttributes) {
      this.eventAttributes = eventAttributes;
      return this;
    }

    /**
     * <p>Required if type is <code>metric</code>. The metric increment that triggers the points.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage metricThreshold(Integer metricThreshold) {
      this.metricThreshold = Optional.ofNullable(metricThreshold);
      return this;
    }

    /**
     * <p>Required if type is <code>metric</code>. The metric increment that triggers the points.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "metricThreshold",
        nulls = Nulls.SKIP
    )
    public _FinalStage metricThreshold(Optional<Integer> metricThreshold) {
      this.metricThreshold = metricThreshold;
      return this;
    }

    /**
     * <p>Required if type is <code>metric</code>. The UUID of the metric.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage metricId(String metricId) {
      this.metricId = Optional.ofNullable(metricId);
      return this;
    }

    /**
     * <p>Required if type is <code>metric</code>. The UUID of the metric.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "metricId",
        nulls = Nulls.SKIP
    )
    public _FinalStage metricId(Optional<String> metricId) {
      this.metricId = metricId;
      return this;
    }

    /**
     * <p>Optional user attribute filters for the trigger.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage userAttributes(
        List<CreatePointsTriggerRequestItemUserAttributesItem> userAttributes) {
      this.userAttributes = Optional.ofNullable(userAttributes);
      return this;
    }

    /**
     * <p>Optional user attribute filters for the trigger.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "userAttributes",
        nulls = Nulls.SKIP
    )
    public _FinalStage userAttributes(
        Optional<List<CreatePointsTriggerRequestItemUserAttributesItem>> userAttributes) {
      this.userAttributes = userAttributes;
      return this;
    }

    /**
     * <p>The status of the trigger. Defaults to 'inactive'.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage status(CreatePointsTriggerRequestItemStatus status) {
      this.status = Optional.ofNullable(status);
      return this;
    }

    /**
     * <p>The status of the trigger. Defaults to 'inactive'.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "status",
        nulls = Nulls.SKIP
    )
    public _FinalStage status(Optional<CreatePointsTriggerRequestItemStatus> status) {
      this.status = status;
      return this;
    }

    @java.lang.Override
    public CreatePointsTriggerRequestItem build() {
      return new CreatePointsTriggerRequestItem(type, points, status, userAttributes, metricId, metricThreshold, eventAttributes, achievementId, streakLength, timeUnit, timeInterval, blockIfOutOfPoints, additionalProperties);
    }
  }
}
