package so.trophy.types;

/**
 * This file was auto-generated by Fern from our API Definition.
 */


import java.lang.Integer;
import java.lang.String;
import java.util.Optional;

public interface IAdminPointsSystem {
  String getId();

  String getName();

  String getKey();

  String getDescription();

  AdminPointsSystemStatus getStatus();

  Optional<AdminPointsSystemBadge> getBadge();

  Optional<Integer> getMaxPoints();
}
