package so.trophy.types;

/**
 * This file was auto-generated by Fern from our API Definition.
 */


import java.lang.String;
import java.util.Optional;

public interface IBaseStreakResponse {
  int getLength();

  StreakFrequency getFrequency();

  Optional<String> getStarted();

  Optional<String> getPeriodStart();

  Optional<String> getPeriodEnd();

  Optional<String> getExpires();
}
