package so.trophy.types;

/**
 * This file was auto-generated by Fern from our API Definition.
 */


import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import so.trophy.core.ObjectMappers;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = MetricEventLeaderboardResponse.Builder.class
)
public final class MetricEventLeaderboardResponse {
  private final Optional<String> end;

  private final Optional<Integer> rank;

  private final Optional<Integer> previousRank;

  private final double threshold;

  private final String id;

  private final String name;

  private final String key;

  private final Optional<LeaderboardResponseStatus> status;

  private final LeaderboardResponseRankBy rankBy;

  private final Optional<String> metricKey;

  private final Optional<String> metricName;

  private final Optional<String> pointsSystemKey;

  private final Optional<String> pointsSystemName;

  private final Optional<String> description;

  private final String start;

  private final int maxParticipants;

  private final Optional<String> runUnit;

  private final int runInterval;

  private final Map<String, Object> additionalProperties;

  private MetricEventLeaderboardResponse(Optional<String> end, Optional<Integer> rank,
      Optional<Integer> previousRank, double threshold, String id, String name, String key,
      Optional<LeaderboardResponseStatus> status, LeaderboardResponseRankBy rankBy,
      Optional<String> metricKey, Optional<String> metricName, Optional<String> pointsSystemKey,
      Optional<String> pointsSystemName, Optional<String> description, String start,
      int maxParticipants, Optional<String> runUnit, int runInterval,
      Map<String, Object> additionalProperties) {
    this.end = end;
    this.rank = rank;
    this.previousRank = previousRank;
    this.threshold = threshold;
    this.id = id;
    this.name = name;
    this.key = key;
    this.status = status;
    this.rankBy = rankBy;
    this.metricKey = metricKey;
    this.metricName = metricName;
    this.pointsSystemKey = pointsSystemKey;
    this.pointsSystemName = pointsSystemName;
    this.description = description;
    this.start = start;
    this.maxParticipants = maxParticipants;
    this.runUnit = runUnit;
    this.runInterval = runInterval;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The end date of the current run of the leaderboard, or null if the run never ends.
   */
  @JsonProperty("end")
  public Optional<String> getEnd() {
    return end;
  }

  /**
   * @return The user's rank in the leaderboard, or null if the user is not on the leaderboard.
   */
  @JsonProperty("rank")
  public Optional<Integer> getRank() {
    return rank;
  }

  /**
   * @return The user's rank in the leaderboard before the event, or null if the user was not on the leaderboard before the event.
   */
  @JsonProperty("previousRank")
  public Optional<Integer> getPreviousRank() {
    return previousRank;
  }

  /**
   * @return The minimum value required to enter the leaderboard according to its current rankings.
   */
  @JsonProperty("threshold")
  public double getThreshold() {
    return threshold;
  }

  /**
   * @return The unique ID of the leaderboard.
   */
  @JsonProperty("id")
  public String getId() {
    return id;
  }

  /**
   * @return The user-facing name of the leaderboard.
   */
  @JsonProperty("name")
  public String getName() {
    return name;
  }

  /**
   * @return The unique key used to reference the leaderboard in APIs.
   */
  @JsonProperty("key")
  public String getKey() {
    return key;
  }

  /**
   * @return The status of the leaderboard.
   */
  @JsonProperty("status")
  public Optional<LeaderboardResponseStatus> getStatus() {
    return status;
  }

  /**
   * @return What the leaderboard ranks by.
   */
  @JsonProperty("rankBy")
  public LeaderboardResponseRankBy getRankBy() {
    return rankBy;
  }

  /**
   * @return The key of the metric to rank by, if rankBy is 'metric'.
   */
  @JsonProperty("metricKey")
  public Optional<String> getMetricKey() {
    return metricKey;
  }

  /**
   * @return The name of the metric to rank by, if rankBy is 'metric'.
   */
  @JsonProperty("metricName")
  public Optional<String> getMetricName() {
    return metricName;
  }

  /**
   * @return The key of the points system to rank by, if rankBy is 'points'.
   */
  @JsonProperty("pointsSystemKey")
  public Optional<String> getPointsSystemKey() {
    return pointsSystemKey;
  }

  /**
   * @return The name of the points system to rank by, if rankBy is 'points'.
   */
  @JsonProperty("pointsSystemName")
  public Optional<String> getPointsSystemName() {
    return pointsSystemName;
  }

  /**
   * @return The user-facing description of the leaderboard.
   */
  @JsonProperty("description")
  public Optional<String> getDescription() {
    return description;
  }

  /**
   * @return The start date of the leaderboard in YYYY-MM-DD format.
   */
  @JsonProperty("start")
  public String getStart() {
    return start;
  }

  /**
   * @return The maximum number of participants in the leaderboard.
   */
  @JsonProperty("maxParticipants")
  public int getMaxParticipants() {
    return maxParticipants;
  }

  /**
   * @return The repetition type for recurring leaderboards, or null for one-time leaderboards.
   */
  @JsonProperty("runUnit")
  public Optional<String> getRunUnit() {
    return runUnit;
  }

  /**
   * @return The interval between repetitions, relative to the start date and repetition type.
   */
  @JsonProperty("runInterval")
  public int getRunInterval() {
    return runInterval;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof MetricEventLeaderboardResponse && equalTo((MetricEventLeaderboardResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(MetricEventLeaderboardResponse other) {
    return end.equals(other.end) && rank.equals(other.rank) && previousRank.equals(other.previousRank) && threshold == other.threshold && id.equals(other.id) && name.equals(other.name) && key.equals(other.key) && status.equals(other.status) && rankBy.equals(other.rankBy) && metricKey.equals(other.metricKey) && metricName.equals(other.metricName) && pointsSystemKey.equals(other.pointsSystemKey) && pointsSystemName.equals(other.pointsSystemName) && description.equals(other.description) && start.equals(other.start) && maxParticipants == other.maxParticipants && runUnit.equals(other.runUnit) && runInterval == other.runInterval;
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.end, this.rank, this.previousRank, this.threshold, this.id, this.name, this.key, this.status, this.rankBy, this.metricKey, this.metricName, this.pointsSystemKey, this.pointsSystemName, this.description, this.start, this.maxParticipants, this.runUnit, this.runInterval);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static ThresholdStage builder() {
    return new Builder();
  }

  public interface ThresholdStage {
    IdStage threshold(double threshold);

    Builder from(MetricEventLeaderboardResponse other);
  }

  public interface IdStage {
    NameStage id(@NotNull String id);
  }

  public interface NameStage {
    KeyStage name(@NotNull String name);
  }

  public interface KeyStage {
    RankByStage key(@NotNull String key);
  }

  public interface RankByStage {
    StartStage rankBy(@NotNull LeaderboardResponseRankBy rankBy);
  }

  public interface StartStage {
    MaxParticipantsStage start(@NotNull String start);
  }

  public interface MaxParticipantsStage {
    RunIntervalStage maxParticipants(int maxParticipants);
  }

  public interface RunIntervalStage {
    _FinalStage runInterval(int runInterval);
  }

  public interface _FinalStage {
    MetricEventLeaderboardResponse build();

    _FinalStage end(Optional<String> end);

    _FinalStage end(String end);

    _FinalStage rank(Optional<Integer> rank);

    _FinalStage rank(Integer rank);

    _FinalStage previousRank(Optional<Integer> previousRank);

    _FinalStage previousRank(Integer previousRank);

    _FinalStage status(Optional<LeaderboardResponseStatus> status);

    _FinalStage status(LeaderboardResponseStatus status);

    _FinalStage metricKey(Optional<String> metricKey);

    _FinalStage metricKey(String metricKey);

    _FinalStage metricName(Optional<String> metricName);

    _FinalStage metricName(String metricName);

    _FinalStage pointsSystemKey(Optional<String> pointsSystemKey);

    _FinalStage pointsSystemKey(String pointsSystemKey);

    _FinalStage pointsSystemName(Optional<String> pointsSystemName);

    _FinalStage pointsSystemName(String pointsSystemName);

    _FinalStage description(Optional<String> description);

    _FinalStage description(String description);

    _FinalStage runUnit(Optional<String> runUnit);

    _FinalStage runUnit(String runUnit);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements ThresholdStage, IdStage, NameStage, KeyStage, RankByStage, StartStage, MaxParticipantsStage, RunIntervalStage, _FinalStage {
    private double threshold;

    private String id;

    private String name;

    private String key;

    private LeaderboardResponseRankBy rankBy;

    private String start;

    private int maxParticipants;

    private int runInterval;

    private Optional<String> runUnit = Optional.empty();

    private Optional<String> description = Optional.empty();

    private Optional<String> pointsSystemName = Optional.empty();

    private Optional<String> pointsSystemKey = Optional.empty();

    private Optional<String> metricName = Optional.empty();

    private Optional<String> metricKey = Optional.empty();

    private Optional<LeaderboardResponseStatus> status = Optional.empty();

    private Optional<Integer> previousRank = Optional.empty();

    private Optional<Integer> rank = Optional.empty();

    private Optional<String> end = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(MetricEventLeaderboardResponse other) {
      end(other.getEnd());
      rank(other.getRank());
      previousRank(other.getPreviousRank());
      threshold(other.getThreshold());
      id(other.getId());
      name(other.getName());
      key(other.getKey());
      status(other.getStatus());
      rankBy(other.getRankBy());
      metricKey(other.getMetricKey());
      metricName(other.getMetricName());
      pointsSystemKey(other.getPointsSystemKey());
      pointsSystemName(other.getPointsSystemName());
      description(other.getDescription());
      start(other.getStart());
      maxParticipants(other.getMaxParticipants());
      runUnit(other.getRunUnit());
      runInterval(other.getRunInterval());
      return this;
    }

    /**
     * <p>The minimum value required to enter the leaderboard according to its current rankings.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("threshold")
    public IdStage threshold(double threshold) {
      this.threshold = threshold;
      return this;
    }

    /**
     * <p>The unique ID of the leaderboard.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("id")
    public NameStage id(@NotNull String id) {
      this.id = Objects.requireNonNull(id, "id must not be null");
      return this;
    }

    /**
     * <p>The user-facing name of the leaderboard.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("name")
    public KeyStage name(@NotNull String name) {
      this.name = Objects.requireNonNull(name, "name must not be null");
      return this;
    }

    /**
     * <p>The unique key used to reference the leaderboard in APIs.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("key")
    public RankByStage key(@NotNull String key) {
      this.key = Objects.requireNonNull(key, "key must not be null");
      return this;
    }

    /**
     * <p>What the leaderboard ranks by.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("rankBy")
    public StartStage rankBy(@NotNull LeaderboardResponseRankBy rankBy) {
      this.rankBy = Objects.requireNonNull(rankBy, "rankBy must not be null");
      return this;
    }

    /**
     * <p>The start date of the leaderboard in YYYY-MM-DD format.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("start")
    public MaxParticipantsStage start(@NotNull String start) {
      this.start = Objects.requireNonNull(start, "start must not be null");
      return this;
    }

    /**
     * <p>The maximum number of participants in the leaderboard.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("maxParticipants")
    public RunIntervalStage maxParticipants(int maxParticipants) {
      this.maxParticipants = maxParticipants;
      return this;
    }

    /**
     * <p>The interval between repetitions, relative to the start date and repetition type.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("runInterval")
    public _FinalStage runInterval(int runInterval) {
      this.runInterval = runInterval;
      return this;
    }

    /**
     * <p>The repetition type for recurring leaderboards, or null for one-time leaderboards.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage runUnit(String runUnit) {
      this.runUnit = Optional.ofNullable(runUnit);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "runUnit",
        nulls = Nulls.SKIP
    )
    public _FinalStage runUnit(Optional<String> runUnit) {
      this.runUnit = runUnit;
      return this;
    }

    /**
     * <p>The user-facing description of the leaderboard.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage description(String description) {
      this.description = Optional.ofNullable(description);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "description",
        nulls = Nulls.SKIP
    )
    public _FinalStage description(Optional<String> description) {
      this.description = description;
      return this;
    }

    /**
     * <p>The name of the points system to rank by, if rankBy is 'points'.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage pointsSystemName(String pointsSystemName) {
      this.pointsSystemName = Optional.ofNullable(pointsSystemName);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "pointsSystemName",
        nulls = Nulls.SKIP
    )
    public _FinalStage pointsSystemName(Optional<String> pointsSystemName) {
      this.pointsSystemName = pointsSystemName;
      return this;
    }

    /**
     * <p>The key of the points system to rank by, if rankBy is 'points'.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage pointsSystemKey(String pointsSystemKey) {
      this.pointsSystemKey = Optional.ofNullable(pointsSystemKey);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "pointsSystemKey",
        nulls = Nulls.SKIP
    )
    public _FinalStage pointsSystemKey(Optional<String> pointsSystemKey) {
      this.pointsSystemKey = pointsSystemKey;
      return this;
    }

    /**
     * <p>The name of the metric to rank by, if rankBy is 'metric'.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage metricName(String metricName) {
      this.metricName = Optional.ofNullable(metricName);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "metricName",
        nulls = Nulls.SKIP
    )
    public _FinalStage metricName(Optional<String> metricName) {
      this.metricName = metricName;
      return this;
    }

    /**
     * <p>The key of the metric to rank by, if rankBy is 'metric'.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage metricKey(String metricKey) {
      this.metricKey = Optional.ofNullable(metricKey);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "metricKey",
        nulls = Nulls.SKIP
    )
    public _FinalStage metricKey(Optional<String> metricKey) {
      this.metricKey = metricKey;
      return this;
    }

    /**
     * <p>The status of the leaderboard.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage status(LeaderboardResponseStatus status) {
      this.status = Optional.ofNullable(status);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "status",
        nulls = Nulls.SKIP
    )
    public _FinalStage status(Optional<LeaderboardResponseStatus> status) {
      this.status = status;
      return this;
    }

    /**
     * <p>The user's rank in the leaderboard before the event, or null if the user was not on the leaderboard before the event.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage previousRank(Integer previousRank) {
      this.previousRank = Optional.ofNullable(previousRank);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "previousRank",
        nulls = Nulls.SKIP
    )
    public _FinalStage previousRank(Optional<Integer> previousRank) {
      this.previousRank = previousRank;
      return this;
    }

    /**
     * <p>The user's rank in the leaderboard, or null if the user is not on the leaderboard.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage rank(Integer rank) {
      this.rank = Optional.ofNullable(rank);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "rank",
        nulls = Nulls.SKIP
    )
    public _FinalStage rank(Optional<Integer> rank) {
      this.rank = rank;
      return this;
    }

    /**
     * <p>The end date of the current run of the leaderboard, or null if the run never ends.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage end(String end) {
      this.end = Optional.ofNullable(end);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "end",
        nulls = Nulls.SKIP
    )
    public _FinalStage end(Optional<String> end) {
      this.end = end;
      return this;
    }

    @java.lang.Override
    public MetricEventLeaderboardResponse build() {
      return new MetricEventLeaderboardResponse(end, rank, previousRank, threshold, id, name, key, status, rankBy, metricKey, metricName, pointsSystemKey, pointsSystemName, description, start, maxParticipants, runUnit, runInterval, additionalProperties);
    }
  }
}
