package so.trophy.types;

/**
 * This file was auto-generated by Fern from our API Definition.
 */


import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import so.trophy.core.ObjectMappers;
import java.lang.Double;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PointsTriggerResponse.Builder.class
)
public final class PointsTriggerResponse {
  private final Optional<String> id;

  private final Optional<PointsTriggerResponseType> type;

  private final Optional<Double> points;

  private final Optional<PointsTriggerResponseStatus> status;

  private final Optional<String> achievementId;

  private final Optional<String> metricId;

  private final Optional<Double> metricThreshold;

  private final Optional<Double> streakLengthThreshold;

  private final Optional<String> metricName;

  private final Optional<String> achievementName;

  private final Optional<List<PointsTriggerResponseUserAttributesItem>> userAttributes;

  private final Optional<PointsTriggerResponseEventAttribute> eventAttribute;

  private final Optional<OffsetDateTime> created;

  private final Optional<OffsetDateTime> updated;

  private final Map<String, Object> additionalProperties;

  private PointsTriggerResponse(Optional<String> id, Optional<PointsTriggerResponseType> type,
      Optional<Double> points, Optional<PointsTriggerResponseStatus> status,
      Optional<String> achievementId, Optional<String> metricId, Optional<Double> metricThreshold,
      Optional<Double> streakLengthThreshold, Optional<String> metricName,
      Optional<String> achievementName,
      Optional<List<PointsTriggerResponseUserAttributesItem>> userAttributes,
      Optional<PointsTriggerResponseEventAttribute> eventAttribute,
      Optional<OffsetDateTime> created, Optional<OffsetDateTime> updated,
      Map<String, Object> additionalProperties) {
    this.id = id;
    this.type = type;
    this.points = points;
    this.status = status;
    this.achievementId = achievementId;
    this.metricId = metricId;
    this.metricThreshold = metricThreshold;
    this.streakLengthThreshold = streakLengthThreshold;
    this.metricName = metricName;
    this.achievementName = achievementName;
    this.userAttributes = userAttributes;
    this.eventAttribute = eventAttribute;
    this.created = created;
    this.updated = updated;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The unique ID of the trigger.
   */
  @JsonProperty("id")
  public Optional<String> getId() {
    return id;
  }

  /**
   * @return The type of trigger.
   */
  @JsonProperty("type")
  public Optional<PointsTriggerResponseType> getType() {
    return type;
  }

  /**
   * @return The points awarded by this trigger.
   */
  @JsonProperty("points")
  public Optional<Double> getPoints() {
    return points;
  }

  /**
   * @return The status of the trigger.
   */
  @JsonProperty("status")
  public Optional<PointsTriggerResponseStatus> getStatus() {
    return status;
  }

  /**
   * @return The unique ID of the achievement associated with this trigger, if the trigger is an achievement.
   */
  @JsonProperty("achievementId")
  public Optional<String> getAchievementId() {
    return achievementId;
  }

  /**
   * @return The unique ID of the metric associated with this trigger, if the trigger is a metric.
   */
  @JsonProperty("metricId")
  public Optional<String> getMetricId() {
    return metricId;
  }

  /**
   * @return The amount that a user must increase the metric to earn the points, if the trigger is a metric.
   */
  @JsonProperty("metricThreshold")
  public Optional<Double> getMetricThreshold() {
    return metricThreshold;
  }

  /**
   * @return The number of consecutive streak periods that a user must complete to earn the points, if the trigger is a streak.
   */
  @JsonProperty("streakLengthThreshold")
  public Optional<Double> getStreakLengthThreshold() {
    return streakLengthThreshold;
  }

  /**
   * @return The name of the metric associated with this trigger, if the trigger is a metric.
   */
  @JsonProperty("metricName")
  public Optional<String> getMetricName() {
    return metricName;
  }

  /**
   * @return The name of the achievement associated with this trigger, if the trigger is an achievement.
   */
  @JsonProperty("achievementName")
  public Optional<String> getAchievementName() {
    return achievementName;
  }

  /**
   * @return User attribute filters that must be met for this trigger to activate. Only present if the trigger has user attribute filters configured.
   */
  @JsonProperty("userAttributes")
  public Optional<List<PointsTriggerResponseUserAttributesItem>> getUserAttributes() {
    return userAttributes;
  }

  /**
   * @return Event attribute filter that must be met for this trigger to activate. Only present if the trigger has an event filter configured.
   */
  @JsonProperty("eventAttribute")
  public Optional<PointsTriggerResponseEventAttribute> getEventAttribute() {
    return eventAttribute;
  }

  /**
   * @return The date and time the trigger was created, in ISO 8601 format.
   */
  @JsonProperty("created")
  public Optional<OffsetDateTime> getCreated() {
    return created;
  }

  /**
   * @return The date and time the trigger was last updated, in ISO 8601 format.
   */
  @JsonProperty("updated")
  public Optional<OffsetDateTime> getUpdated() {
    return updated;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PointsTriggerResponse && equalTo((PointsTriggerResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PointsTriggerResponse other) {
    return id.equals(other.id) && type.equals(other.type) && points.equals(other.points) && status.equals(other.status) && achievementId.equals(other.achievementId) && metricId.equals(other.metricId) && metricThreshold.equals(other.metricThreshold) && streakLengthThreshold.equals(other.streakLengthThreshold) && metricName.equals(other.metricName) && achievementName.equals(other.achievementName) && userAttributes.equals(other.userAttributes) && eventAttribute.equals(other.eventAttribute) && created.equals(other.created) && updated.equals(other.updated);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.type, this.points, this.status, this.achievementId, this.metricId, this.metricThreshold, this.streakLengthThreshold, this.metricName, this.achievementName, this.userAttributes, this.eventAttribute, this.created, this.updated);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> id = Optional.empty();

    private Optional<PointsTriggerResponseType> type = Optional.empty();

    private Optional<Double> points = Optional.empty();

    private Optional<PointsTriggerResponseStatus> status = Optional.empty();

    private Optional<String> achievementId = Optional.empty();

    private Optional<String> metricId = Optional.empty();

    private Optional<Double> metricThreshold = Optional.empty();

    private Optional<Double> streakLengthThreshold = Optional.empty();

    private Optional<String> metricName = Optional.empty();

    private Optional<String> achievementName = Optional.empty();

    private Optional<List<PointsTriggerResponseUserAttributesItem>> userAttributes = Optional.empty();

    private Optional<PointsTriggerResponseEventAttribute> eventAttribute = Optional.empty();

    private Optional<OffsetDateTime> created = Optional.empty();

    private Optional<OffsetDateTime> updated = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(PointsTriggerResponse other) {
      id(other.getId());
      type(other.getType());
      points(other.getPoints());
      status(other.getStatus());
      achievementId(other.getAchievementId());
      metricId(other.getMetricId());
      metricThreshold(other.getMetricThreshold());
      streakLengthThreshold(other.getStreakLengthThreshold());
      metricName(other.getMetricName());
      achievementName(other.getAchievementName());
      userAttributes(other.getUserAttributes());
      eventAttribute(other.getEventAttribute());
      created(other.getCreated());
      updated(other.getUpdated());
      return this;
    }

    @JsonSetter(
        value = "id",
        nulls = Nulls.SKIP
    )
    public Builder id(Optional<String> id) {
      this.id = id;
      return this;
    }

    public Builder id(String id) {
      this.id = Optional.ofNullable(id);
      return this;
    }

    @JsonSetter(
        value = "type",
        nulls = Nulls.SKIP
    )
    public Builder type(Optional<PointsTriggerResponseType> type) {
      this.type = type;
      return this;
    }

    public Builder type(PointsTriggerResponseType type) {
      this.type = Optional.ofNullable(type);
      return this;
    }

    @JsonSetter(
        value = "points",
        nulls = Nulls.SKIP
    )
    public Builder points(Optional<Double> points) {
      this.points = points;
      return this;
    }

    public Builder points(Double points) {
      this.points = Optional.ofNullable(points);
      return this;
    }

    @JsonSetter(
        value = "status",
        nulls = Nulls.SKIP
    )
    public Builder status(Optional<PointsTriggerResponseStatus> status) {
      this.status = status;
      return this;
    }

    public Builder status(PointsTriggerResponseStatus status) {
      this.status = Optional.ofNullable(status);
      return this;
    }

    @JsonSetter(
        value = "achievementId",
        nulls = Nulls.SKIP
    )
    public Builder achievementId(Optional<String> achievementId) {
      this.achievementId = achievementId;
      return this;
    }

    public Builder achievementId(String achievementId) {
      this.achievementId = Optional.ofNullable(achievementId);
      return this;
    }

    @JsonSetter(
        value = "metricId",
        nulls = Nulls.SKIP
    )
    public Builder metricId(Optional<String> metricId) {
      this.metricId = metricId;
      return this;
    }

    public Builder metricId(String metricId) {
      this.metricId = Optional.ofNullable(metricId);
      return this;
    }

    @JsonSetter(
        value = "metricThreshold",
        nulls = Nulls.SKIP
    )
    public Builder metricThreshold(Optional<Double> metricThreshold) {
      this.metricThreshold = metricThreshold;
      return this;
    }

    public Builder metricThreshold(Double metricThreshold) {
      this.metricThreshold = Optional.ofNullable(metricThreshold);
      return this;
    }

    @JsonSetter(
        value = "streakLengthThreshold",
        nulls = Nulls.SKIP
    )
    public Builder streakLengthThreshold(Optional<Double> streakLengthThreshold) {
      this.streakLengthThreshold = streakLengthThreshold;
      return this;
    }

    public Builder streakLengthThreshold(Double streakLengthThreshold) {
      this.streakLengthThreshold = Optional.ofNullable(streakLengthThreshold);
      return this;
    }

    @JsonSetter(
        value = "metricName",
        nulls = Nulls.SKIP
    )
    public Builder metricName(Optional<String> metricName) {
      this.metricName = metricName;
      return this;
    }

    public Builder metricName(String metricName) {
      this.metricName = Optional.ofNullable(metricName);
      return this;
    }

    @JsonSetter(
        value = "achievementName",
        nulls = Nulls.SKIP
    )
    public Builder achievementName(Optional<String> achievementName) {
      this.achievementName = achievementName;
      return this;
    }

    public Builder achievementName(String achievementName) {
      this.achievementName = Optional.ofNullable(achievementName);
      return this;
    }

    @JsonSetter(
        value = "userAttributes",
        nulls = Nulls.SKIP
    )
    public Builder userAttributes(
        Optional<List<PointsTriggerResponseUserAttributesItem>> userAttributes) {
      this.userAttributes = userAttributes;
      return this;
    }

    public Builder userAttributes(List<PointsTriggerResponseUserAttributesItem> userAttributes) {
      this.userAttributes = Optional.ofNullable(userAttributes);
      return this;
    }

    @JsonSetter(
        value = "eventAttribute",
        nulls = Nulls.SKIP
    )
    public Builder eventAttribute(Optional<PointsTriggerResponseEventAttribute> eventAttribute) {
      this.eventAttribute = eventAttribute;
      return this;
    }

    public Builder eventAttribute(PointsTriggerResponseEventAttribute eventAttribute) {
      this.eventAttribute = Optional.ofNullable(eventAttribute);
      return this;
    }

    @JsonSetter(
        value = "created",
        nulls = Nulls.SKIP
    )
    public Builder created(Optional<OffsetDateTime> created) {
      this.created = created;
      return this;
    }

    public Builder created(OffsetDateTime created) {
      this.created = Optional.ofNullable(created);
      return this;
    }

    @JsonSetter(
        value = "updated",
        nulls = Nulls.SKIP
    )
    public Builder updated(Optional<OffsetDateTime> updated) {
      this.updated = updated;
      return this;
    }

    public Builder updated(OffsetDateTime updated) {
      this.updated = Optional.ofNullable(updated);
      return this;
    }

    public PointsTriggerResponse build() {
      return new PointsTriggerResponse(id, type, points, status, achievementId, metricId, metricThreshold, streakLengthThreshold, metricName, achievementName, userAttributes, eventAttribute, created, updated, additionalProperties);
    }
  }
}
