package so.trophy.types;

/**
 * This file was auto-generated by Fern from our API Definition.
 */


import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import so.trophy.core.ObjectMappers;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PointsTrigger.Builder.class
)
public final class PointsTrigger {
  private final String id;

  private final PointsTriggerType type;

  private final int points;

  private final PointsTriggerStatus status;

  private final Optional<String> achievementId;

  private final Optional<String> metricId;

  private final Optional<String> metricName;

  private final Optional<Integer> metricThreshold;

  private final Optional<Integer> streakLengthThreshold;

  private final Optional<String> achievementName;

  private final Optional<PointsTriggerTimeUnit> timeUnit;

  private final Optional<Integer> timeInterval;

  private final List<PointsTriggerUserAttributesItem> userAttributes;

  private final Optional<PointsTriggerEventAttribute> eventAttribute;

  private final Optional<List<PointsTriggerEventAttributesItem>> eventAttributes;

  private final OffsetDateTime created;

  private final OffsetDateTime updated;

  private final Map<String, Object> additionalProperties;

  private PointsTrigger(String id, PointsTriggerType type, int points, PointsTriggerStatus status,
      Optional<String> achievementId, Optional<String> metricId, Optional<String> metricName,
      Optional<Integer> metricThreshold, Optional<Integer> streakLengthThreshold,
      Optional<String> achievementName, Optional<PointsTriggerTimeUnit> timeUnit,
      Optional<Integer> timeInterval, List<PointsTriggerUserAttributesItem> userAttributes,
      Optional<PointsTriggerEventAttribute> eventAttribute,
      Optional<List<PointsTriggerEventAttributesItem>> eventAttributes, OffsetDateTime created,
      OffsetDateTime updated, Map<String, Object> additionalProperties) {
    this.id = id;
    this.type = type;
    this.points = points;
    this.status = status;
    this.achievementId = achievementId;
    this.metricId = metricId;
    this.metricName = metricName;
    this.metricThreshold = metricThreshold;
    this.streakLengthThreshold = streakLengthThreshold;
    this.achievementName = achievementName;
    this.timeUnit = timeUnit;
    this.timeInterval = timeInterval;
    this.userAttributes = userAttributes;
    this.eventAttribute = eventAttribute;
    this.eventAttributes = eventAttributes;
    this.created = created;
    this.updated = updated;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The ID of the trigger
   */
  @JsonProperty("id")
  public String getId() {
    return id;
  }

  /**
   * @return The type of trigger
   */
  @JsonProperty("type")
  public PointsTriggerType getType() {
    return type;
  }

  /**
   * @return The points awarded by this trigger.
   */
  @JsonProperty("points")
  public int getPoints() {
    return points;
  }

  /**
   * @return The status of the trigger.
   */
  @JsonProperty("status")
  public PointsTriggerStatus getStatus() {
    return status;
  }

  /**
   * @return The unique ID of the achievement associated with this trigger, if the trigger is an achievement.
   */
  @JsonProperty("achievementId")
  public Optional<String> getAchievementId() {
    return achievementId;
  }

  /**
   * @return The unique ID of the metric associated with this trigger, if the trigger is a metric.
   */
  @JsonProperty("metricId")
  public Optional<String> getMetricId() {
    return metricId;
  }

  /**
   * @return If the trigger has type 'metric', the name of the metric
   */
  @JsonProperty("metricName")
  public Optional<String> getMetricName() {
    return metricName;
  }

  /**
   * @return If the trigger has type 'metric', the threshold of the metric that triggers the points
   */
  @JsonProperty("metricThreshold")
  public Optional<Integer> getMetricThreshold() {
    return metricThreshold;
  }

  /**
   * @return If the trigger has type 'streak', the threshold of the streak that triggers the points
   */
  @JsonProperty("streakLengthThreshold")
  public Optional<Integer> getStreakLengthThreshold() {
    return streakLengthThreshold;
  }

  /**
   * @return If the trigger has type 'achievement', the name of the achievement
   */
  @JsonProperty("achievementName")
  public Optional<String> getAchievementName() {
    return achievementName;
  }

  /**
   * @return If the trigger has type 'time', the unit of time after which to award points
   */
  @JsonProperty("timeUnit")
  public Optional<PointsTriggerTimeUnit> getTimeUnit() {
    return timeUnit;
  }

  /**
   * @return If the trigger has type 'time', the numer of units of timeUnit after which to award points
   */
  @JsonProperty("timeInterval")
  public Optional<Integer> getTimeInterval() {
    return timeInterval;
  }

  /**
   * @return User attribute filters that must be met for this trigger to award points. Empty when the trigger has no user attribute filters configured.
   */
  @JsonProperty("userAttributes")
  public List<PointsTriggerUserAttributesItem> getUserAttributes() {
    return userAttributes;
  }

  /**
   * @return Deprecated. Event attribute filter that must be met for this trigger to award points. Only present if the trigger has an event filter configured.
   */
  @JsonProperty("eventAttribute")
  public Optional<PointsTriggerEventAttribute> getEventAttribute() {
    return eventAttribute;
  }

  /**
   * @return If the trigger has type 'metric', the event attributes that must match for the trigger to award points. Empty when the trigger is metric-based and has no event attribute filters. Omitted for non-metric triggers.
   */
  @JsonProperty("eventAttributes")
  public Optional<List<PointsTriggerEventAttributesItem>> getEventAttributes() {
    return eventAttributes;
  }

  /**
   * @return The date and time the trigger was created, in ISO 8601 format.
   */
  @JsonProperty("created")
  public OffsetDateTime getCreated() {
    return created;
  }

  /**
   * @return The date and time the trigger was last updated, in ISO 8601 format.
   */
  @JsonProperty("updated")
  public OffsetDateTime getUpdated() {
    return updated;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PointsTrigger && equalTo((PointsTrigger) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PointsTrigger other) {
    return id.equals(other.id) && type.equals(other.type) && points == other.points && status.equals(other.status) && achievementId.equals(other.achievementId) && metricId.equals(other.metricId) && metricName.equals(other.metricName) && metricThreshold.equals(other.metricThreshold) && streakLengthThreshold.equals(other.streakLengthThreshold) && achievementName.equals(other.achievementName) && timeUnit.equals(other.timeUnit) && timeInterval.equals(other.timeInterval) && userAttributes.equals(other.userAttributes) && eventAttribute.equals(other.eventAttribute) && eventAttributes.equals(other.eventAttributes) && created.equals(other.created) && updated.equals(other.updated);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.type, this.points, this.status, this.achievementId, this.metricId, this.metricName, this.metricThreshold, this.streakLengthThreshold, this.achievementName, this.timeUnit, this.timeInterval, this.userAttributes, this.eventAttribute, this.eventAttributes, this.created, this.updated);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static IdStage builder() {
    return new Builder();
  }

  public interface IdStage {
    /**
     * <p>The ID of the trigger</p>
     */
    TypeStage id(@NotNull String id);

    Builder from(PointsTrigger other);
  }

  public interface TypeStage {
    /**
     * <p>The type of trigger</p>
     */
    PointsStage type(@NotNull PointsTriggerType type);
  }

  public interface PointsStage {
    /**
     * <p>The points awarded by this trigger.</p>
     */
    StatusStage points(int points);
  }

  public interface StatusStage {
    /**
     * <p>The status of the trigger.</p>
     */
    CreatedStage status(@NotNull PointsTriggerStatus status);
  }

  public interface CreatedStage {
    /**
     * <p>The date and time the trigger was created, in ISO 8601 format.</p>
     */
    UpdatedStage created(@NotNull OffsetDateTime created);
  }

  public interface UpdatedStage {
    /**
     * <p>The date and time the trigger was last updated, in ISO 8601 format.</p>
     */
    _FinalStage updated(@NotNull OffsetDateTime updated);
  }

  public interface _FinalStage {
    PointsTrigger build();

    /**
     * <p>The unique ID of the achievement associated with this trigger, if the trigger is an achievement.</p>
     */
    _FinalStage achievementId(Optional<String> achievementId);

    _FinalStage achievementId(String achievementId);

    /**
     * <p>The unique ID of the metric associated with this trigger, if the trigger is a metric.</p>
     */
    _FinalStage metricId(Optional<String> metricId);

    _FinalStage metricId(String metricId);

    /**
     * <p>If the trigger has type 'metric', the name of the metric</p>
     */
    _FinalStage metricName(Optional<String> metricName);

    _FinalStage metricName(String metricName);

    /**
     * <p>If the trigger has type 'metric', the threshold of the metric that triggers the points</p>
     */
    _FinalStage metricThreshold(Optional<Integer> metricThreshold);

    _FinalStage metricThreshold(Integer metricThreshold);

    /**
     * <p>If the trigger has type 'streak', the threshold of the streak that triggers the points</p>
     */
    _FinalStage streakLengthThreshold(Optional<Integer> streakLengthThreshold);

    _FinalStage streakLengthThreshold(Integer streakLengthThreshold);

    /**
     * <p>If the trigger has type 'achievement', the name of the achievement</p>
     */
    _FinalStage achievementName(Optional<String> achievementName);

    _FinalStage achievementName(String achievementName);

    /**
     * <p>If the trigger has type 'time', the unit of time after which to award points</p>
     */
    _FinalStage timeUnit(Optional<PointsTriggerTimeUnit> timeUnit);

    _FinalStage timeUnit(PointsTriggerTimeUnit timeUnit);

    /**
     * <p>If the trigger has type 'time', the numer of units of timeUnit after which to award points</p>
     */
    _FinalStage timeInterval(Optional<Integer> timeInterval);

    _FinalStage timeInterval(Integer timeInterval);

    /**
     * <p>User attribute filters that must be met for this trigger to award points. Empty when the trigger has no user attribute filters configured.</p>
     */
    _FinalStage userAttributes(List<PointsTriggerUserAttributesItem> userAttributes);

    _FinalStage addUserAttributes(PointsTriggerUserAttributesItem userAttributes);

    _FinalStage addAllUserAttributes(List<PointsTriggerUserAttributesItem> userAttributes);

    /**
     * <p>Deprecated. Event attribute filter that must be met for this trigger to award points. Only present if the trigger has an event filter configured.</p>
     */
    _FinalStage eventAttribute(Optional<PointsTriggerEventAttribute> eventAttribute);

    _FinalStage eventAttribute(PointsTriggerEventAttribute eventAttribute);

    /**
     * <p>If the trigger has type 'metric', the event attributes that must match for the trigger to award points. Empty when the trigger is metric-based and has no event attribute filters. Omitted for non-metric triggers.</p>
     */
    _FinalStage eventAttributes(Optional<List<PointsTriggerEventAttributesItem>> eventAttributes);

    _FinalStage eventAttributes(List<PointsTriggerEventAttributesItem> eventAttributes);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements IdStage, TypeStage, PointsStage, StatusStage, CreatedStage, UpdatedStage, _FinalStage {
    private String id;

    private PointsTriggerType type;

    private int points;

    private PointsTriggerStatus status;

    private OffsetDateTime created;

    private OffsetDateTime updated;

    private Optional<List<PointsTriggerEventAttributesItem>> eventAttributes = Optional.empty();

    private Optional<PointsTriggerEventAttribute> eventAttribute = Optional.empty();

    private List<PointsTriggerUserAttributesItem> userAttributes = new ArrayList<>();

    private Optional<Integer> timeInterval = Optional.empty();

    private Optional<PointsTriggerTimeUnit> timeUnit = Optional.empty();

    private Optional<String> achievementName = Optional.empty();

    private Optional<Integer> streakLengthThreshold = Optional.empty();

    private Optional<Integer> metricThreshold = Optional.empty();

    private Optional<String> metricName = Optional.empty();

    private Optional<String> metricId = Optional.empty();

    private Optional<String> achievementId = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(PointsTrigger other) {
      id(other.getId());
      type(other.getType());
      points(other.getPoints());
      status(other.getStatus());
      achievementId(other.getAchievementId());
      metricId(other.getMetricId());
      metricName(other.getMetricName());
      metricThreshold(other.getMetricThreshold());
      streakLengthThreshold(other.getStreakLengthThreshold());
      achievementName(other.getAchievementName());
      timeUnit(other.getTimeUnit());
      timeInterval(other.getTimeInterval());
      userAttributes(other.getUserAttributes());
      eventAttribute(other.getEventAttribute());
      eventAttributes(other.getEventAttributes());
      created(other.getCreated());
      updated(other.getUpdated());
      return this;
    }

    /**
     * <p>The ID of the trigger</p>
     * <p>The ID of the trigger</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("id")
    public TypeStage id(@NotNull String id) {
      this.id = Objects.requireNonNull(id, "id must not be null");
      return this;
    }

    /**
     * <p>The type of trigger</p>
     * <p>The type of trigger</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("type")
    public PointsStage type(@NotNull PointsTriggerType type) {
      this.type = Objects.requireNonNull(type, "type must not be null");
      return this;
    }

    /**
     * <p>The points awarded by this trigger.</p>
     * <p>The points awarded by this trigger.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("points")
    public StatusStage points(int points) {
      this.points = points;
      return this;
    }

    /**
     * <p>The status of the trigger.</p>
     * <p>The status of the trigger.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("status")
    public CreatedStage status(@NotNull PointsTriggerStatus status) {
      this.status = Objects.requireNonNull(status, "status must not be null");
      return this;
    }

    /**
     * <p>The date and time the trigger was created, in ISO 8601 format.</p>
     * <p>The date and time the trigger was created, in ISO 8601 format.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("created")
    public UpdatedStage created(@NotNull OffsetDateTime created) {
      this.created = Objects.requireNonNull(created, "created must not be null");
      return this;
    }

    /**
     * <p>The date and time the trigger was last updated, in ISO 8601 format.</p>
     * <p>The date and time the trigger was last updated, in ISO 8601 format.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("updated")
    public _FinalStage updated(@NotNull OffsetDateTime updated) {
      this.updated = Objects.requireNonNull(updated, "updated must not be null");
      return this;
    }

    /**
     * <p>If the trigger has type 'metric', the event attributes that must match for the trigger to award points. Empty when the trigger is metric-based and has no event attribute filters. Omitted for non-metric triggers.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage eventAttributes(List<PointsTriggerEventAttributesItem> eventAttributes) {
      this.eventAttributes = Optional.ofNullable(eventAttributes);
      return this;
    }

    /**
     * <p>If the trigger has type 'metric', the event attributes that must match for the trigger to award points. Empty when the trigger is metric-based and has no event attribute filters. Omitted for non-metric triggers.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "eventAttributes",
        nulls = Nulls.SKIP
    )
    public _FinalStage eventAttributes(
        Optional<List<PointsTriggerEventAttributesItem>> eventAttributes) {
      this.eventAttributes = eventAttributes;
      return this;
    }

    /**
     * <p>Deprecated. Event attribute filter that must be met for this trigger to award points. Only present if the trigger has an event filter configured.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage eventAttribute(PointsTriggerEventAttribute eventAttribute) {
      this.eventAttribute = Optional.ofNullable(eventAttribute);
      return this;
    }

    /**
     * <p>Deprecated. Event attribute filter that must be met for this trigger to award points. Only present if the trigger has an event filter configured.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "eventAttribute",
        nulls = Nulls.SKIP
    )
    public _FinalStage eventAttribute(Optional<PointsTriggerEventAttribute> eventAttribute) {
      this.eventAttribute = eventAttribute;
      return this;
    }

    /**
     * <p>User attribute filters that must be met for this trigger to award points. Empty when the trigger has no user attribute filters configured.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addAllUserAttributes(List<PointsTriggerUserAttributesItem> userAttributes) {
      if (userAttributes != null) {
        this.userAttributes.addAll(userAttributes);
      }
      return this;
    }

    /**
     * <p>User attribute filters that must be met for this trigger to award points. Empty when the trigger has no user attribute filters configured.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addUserAttributes(PointsTriggerUserAttributesItem userAttributes) {
      this.userAttributes.add(userAttributes);
      return this;
    }

    /**
     * <p>User attribute filters that must be met for this trigger to award points. Empty when the trigger has no user attribute filters configured.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "userAttributes",
        nulls = Nulls.SKIP
    )
    public _FinalStage userAttributes(List<PointsTriggerUserAttributesItem> userAttributes) {
      this.userAttributes.clear();
      this.userAttributes.addAll(userAttributes);
      return this;
    }

    /**
     * <p>If the trigger has type 'time', the numer of units of timeUnit after which to award points</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage timeInterval(Integer timeInterval) {
      this.timeInterval = Optional.ofNullable(timeInterval);
      return this;
    }

    /**
     * <p>If the trigger has type 'time', the numer of units of timeUnit after which to award points</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "timeInterval",
        nulls = Nulls.SKIP
    )
    public _FinalStage timeInterval(Optional<Integer> timeInterval) {
      this.timeInterval = timeInterval;
      return this;
    }

    /**
     * <p>If the trigger has type 'time', the unit of time after which to award points</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage timeUnit(PointsTriggerTimeUnit timeUnit) {
      this.timeUnit = Optional.ofNullable(timeUnit);
      return this;
    }

    /**
     * <p>If the trigger has type 'time', the unit of time after which to award points</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "timeUnit",
        nulls = Nulls.SKIP
    )
    public _FinalStage timeUnit(Optional<PointsTriggerTimeUnit> timeUnit) {
      this.timeUnit = timeUnit;
      return this;
    }

    /**
     * <p>If the trigger has type 'achievement', the name of the achievement</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage achievementName(String achievementName) {
      this.achievementName = Optional.ofNullable(achievementName);
      return this;
    }

    /**
     * <p>If the trigger has type 'achievement', the name of the achievement</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "achievementName",
        nulls = Nulls.SKIP
    )
    public _FinalStage achievementName(Optional<String> achievementName) {
      this.achievementName = achievementName;
      return this;
    }

    /**
     * <p>If the trigger has type 'streak', the threshold of the streak that triggers the points</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage streakLengthThreshold(Integer streakLengthThreshold) {
      this.streakLengthThreshold = Optional.ofNullable(streakLengthThreshold);
      return this;
    }

    /**
     * <p>If the trigger has type 'streak', the threshold of the streak that triggers the points</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "streakLengthThreshold",
        nulls = Nulls.SKIP
    )
    public _FinalStage streakLengthThreshold(Optional<Integer> streakLengthThreshold) {
      this.streakLengthThreshold = streakLengthThreshold;
      return this;
    }

    /**
     * <p>If the trigger has type 'metric', the threshold of the metric that triggers the points</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage metricThreshold(Integer metricThreshold) {
      this.metricThreshold = Optional.ofNullable(metricThreshold);
      return this;
    }

    /**
     * <p>If the trigger has type 'metric', the threshold of the metric that triggers the points</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "metricThreshold",
        nulls = Nulls.SKIP
    )
    public _FinalStage metricThreshold(Optional<Integer> metricThreshold) {
      this.metricThreshold = metricThreshold;
      return this;
    }

    /**
     * <p>If the trigger has type 'metric', the name of the metric</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage metricName(String metricName) {
      this.metricName = Optional.ofNullable(metricName);
      return this;
    }

    /**
     * <p>If the trigger has type 'metric', the name of the metric</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "metricName",
        nulls = Nulls.SKIP
    )
    public _FinalStage metricName(Optional<String> metricName) {
      this.metricName = metricName;
      return this;
    }

    /**
     * <p>The unique ID of the metric associated with this trigger, if the trigger is a metric.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage metricId(String metricId) {
      this.metricId = Optional.ofNullable(metricId);
      return this;
    }

    /**
     * <p>The unique ID of the metric associated with this trigger, if the trigger is a metric.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "metricId",
        nulls = Nulls.SKIP
    )
    public _FinalStage metricId(Optional<String> metricId) {
      this.metricId = metricId;
      return this;
    }

    /**
     * <p>The unique ID of the achievement associated with this trigger, if the trigger is an achievement.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage achievementId(String achievementId) {
      this.achievementId = Optional.ofNullable(achievementId);
      return this;
    }

    /**
     * <p>The unique ID of the achievement associated with this trigger, if the trigger is an achievement.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "achievementId",
        nulls = Nulls.SKIP
    )
    public _FinalStage achievementId(Optional<String> achievementId) {
      this.achievementId = achievementId;
      return this;
    }

    @java.lang.Override
    public PointsTrigger build() {
      return new PointsTrigger(id, type, points, status, achievementId, metricId, metricName, metricThreshold, streakLengthThreshold, achievementName, timeUnit, timeInterval, userAttributes, eventAttribute, eventAttributes, created, updated, additionalProperties);
    }
  }
}
