package so.trophy.types;

/**
 * This file was auto-generated by Fern from our API Definition.
 */


import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

public enum PointsTriggerStatus {
  ACTIVE("active"),

  INACTIVE("inactive"),

  ARCHIVED("archived");

  private final String value;

  PointsTriggerStatus(String value) {
    this.value = value;
  }

  @JsonValue
  @java.lang.Override
  public String toString() {
    return this.value;
  }
}
