package so.trophy.types;

/**
 * This file was auto-generated by Fern from our API Definition.
 */


import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import so.trophy.core.ObjectMappers;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = StreakPreferences.Builder.class
)
public final class StreakPreferences {
  private final Optional<Boolean> enabled;

  private final Optional<StreakEvaluationModePreference> evaluationMode;

  private final Optional<List<StreakMetricPreference>> metrics;

  private final Map<String, Object> additionalProperties;

  private StreakPreferences(Optional<Boolean> enabled,
      Optional<StreakEvaluationModePreference> evaluationMode,
      Optional<List<StreakMetricPreference>> metrics, Map<String, Object> additionalProperties) {
    this.enabled = enabled;
    this.evaluationMode = evaluationMode;
    this.metrics = metrics;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Whether streaks are calculated for this user. When false, the user's streak is always 0 and streak webhooks and notifications are not sent.
   */
  @JsonProperty("enabled")
  public Optional<Boolean> getEnabled() {
    return enabled;
  }

  @JsonProperty("evaluationMode")
  public Optional<StreakEvaluationModePreference> getEvaluationMode() {
    return evaluationMode;
  }

  /**
   * @return Metrics and thresholds that count toward this user's streak.
   */
  @JsonProperty("metrics")
  public Optional<List<StreakMetricPreference>> getMetrics() {
    return metrics;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof StreakPreferences && equalTo((StreakPreferences) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(StreakPreferences other) {
    return enabled.equals(other.enabled) && evaluationMode.equals(other.evaluationMode) && metrics.equals(other.metrics);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.enabled, this.evaluationMode, this.metrics);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<Boolean> enabled = Optional.empty();

    private Optional<StreakEvaluationModePreference> evaluationMode = Optional.empty();

    private Optional<List<StreakMetricPreference>> metrics = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(StreakPreferences other) {
      enabled(other.getEnabled());
      evaluationMode(other.getEvaluationMode());
      metrics(other.getMetrics());
      return this;
    }

    /**
     * <p>Whether streaks are calculated for this user. When false, the user's streak is always 0 and streak webhooks and notifications are not sent.</p>
     */
    @JsonSetter(
        value = "enabled",
        nulls = Nulls.SKIP
    )
    public Builder enabled(Optional<Boolean> enabled) {
      this.enabled = enabled;
      return this;
    }

    public Builder enabled(Boolean enabled) {
      this.enabled = Optional.ofNullable(enabled);
      return this;
    }

    @JsonSetter(
        value = "evaluationMode",
        nulls = Nulls.SKIP
    )
    public Builder evaluationMode(Optional<StreakEvaluationModePreference> evaluationMode) {
      this.evaluationMode = evaluationMode;
      return this;
    }

    public Builder evaluationMode(StreakEvaluationModePreference evaluationMode) {
      this.evaluationMode = Optional.ofNullable(evaluationMode);
      return this;
    }

    /**
     * <p>Metrics and thresholds that count toward this user's streak.</p>
     */
    @JsonSetter(
        value = "metrics",
        nulls = Nulls.SKIP
    )
    public Builder metrics(Optional<List<StreakMetricPreference>> metrics) {
      this.metrics = metrics;
      return this;
    }

    public Builder metrics(List<StreakMetricPreference> metrics) {
      this.metrics = Optional.ofNullable(metrics);
      return this;
    }

    public StreakPreferences build() {
      return new StreakPreferences(enabled, evaluationMode, metrics, additionalProperties);
    }
  }
}
