package so.trophy.types;

/**
 * This file was auto-generated by Fern from our API Definition.
 */


import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import so.trophy.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = UpdateAttributeRequestItem.Builder.class
)
public final class UpdateAttributeRequestItem {
  private final String id;

  private final Optional<String> name;

  private final Map<String, Object> additionalProperties;

  private UpdateAttributeRequestItem(String id, Optional<String> name,
      Map<String, Object> additionalProperties) {
    this.id = id;
    this.name = name;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The UUID of the attribute to update.
   */
  @JsonProperty("id")
  public String getId() {
    return id;
  }

  /**
   * @return The updated attribute name.
   */
  @JsonProperty("name")
  public Optional<String> getName() {
    return name;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof UpdateAttributeRequestItem && equalTo((UpdateAttributeRequestItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(UpdateAttributeRequestItem other) {
    return id.equals(other.id) && name.equals(other.name);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.name);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static IdStage builder() {
    return new Builder();
  }

  public interface IdStage {
    /**
     * <p>The UUID of the attribute to update.</p>
     */
    _FinalStage id(@NotNull String id);

    Builder from(UpdateAttributeRequestItem other);
  }

  public interface _FinalStage {
    UpdateAttributeRequestItem build();

    /**
     * <p>The updated attribute name.</p>
     */
    _FinalStage name(Optional<String> name);

    _FinalStage name(String name);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements IdStage, _FinalStage {
    private String id;

    private Optional<String> name = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(UpdateAttributeRequestItem other) {
      id(other.getId());
      name(other.getName());
      return this;
    }

    /**
     * <p>The UUID of the attribute to update.</p>
     * <p>The UUID of the attribute to update.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("id")
    public _FinalStage id(@NotNull String id) {
      this.id = Objects.requireNonNull(id, "id must not be null");
      return this;
    }

    /**
     * <p>The updated attribute name.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage name(String name) {
      this.name = Optional.ofNullable(name);
      return this;
    }

    /**
     * <p>The updated attribute name.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "name",
        nulls = Nulls.SKIP
    )
    public _FinalStage name(Optional<String> name) {
      this.name = name;
      return this;
    }

    @java.lang.Override
    public UpdateAttributeRequestItem build() {
      return new UpdateAttributeRequestItem(id, name, additionalProperties);
    }
  }
}
