package so.trophy.types;

/**
 * This file was auto-generated by Fern from our API Definition.
 */


import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import so.trophy.core.ObjectMappers;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = UpdatePointsSystemRequestItem.Builder.class
)
public final class UpdatePointsSystemRequestItem {
  private final String id;

  private final Optional<String> name;

  private final Optional<String> description;

  private final Optional<UpdatePointsSystemRequestItemBadge> badge;

  private final Optional<Integer> maxPoints;

  private final Map<String, Object> additionalProperties;

  private UpdatePointsSystemRequestItem(String id, Optional<String> name,
      Optional<String> description, Optional<UpdatePointsSystemRequestItemBadge> badge,
      Optional<Integer> maxPoints, Map<String, Object> additionalProperties) {
    this.id = id;
    this.name = name;
    this.description = description;
    this.badge = badge;
    this.maxPoints = maxPoints;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The UUID of the points system to update.
   */
  @JsonProperty("id")
  public String getId() {
    return id;
  }

  /**
   * @return Updated name.
   */
  @JsonProperty("name")
  public Optional<String> getName() {
    return name;
  }

  /**
   * @return Updated description.
   */
  @JsonProperty("description")
  public Optional<String> getDescription() {
    return description;
  }

  /**
   * @return Updated badge. Set to null to remove.
   */
  @JsonProperty("badge")
  public Optional<UpdatePointsSystemRequestItemBadge> getBadge() {
    return badge;
  }

  /**
   * @return Updated max points. Set to null to remove.
   */
  @JsonProperty("maxPoints")
  public Optional<Integer> getMaxPoints() {
    return maxPoints;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof UpdatePointsSystemRequestItem && equalTo((UpdatePointsSystemRequestItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(UpdatePointsSystemRequestItem other) {
    return id.equals(other.id) && name.equals(other.name) && description.equals(other.description) && badge.equals(other.badge) && maxPoints.equals(other.maxPoints);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.name, this.description, this.badge, this.maxPoints);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static IdStage builder() {
    return new Builder();
  }

  public interface IdStage {
    /**
     * <p>The UUID of the points system to update.</p>
     */
    _FinalStage id(@NotNull String id);

    Builder from(UpdatePointsSystemRequestItem other);
  }

  public interface _FinalStage {
    UpdatePointsSystemRequestItem build();

    /**
     * <p>Updated name.</p>
     */
    _FinalStage name(Optional<String> name);

    _FinalStage name(String name);

    /**
     * <p>Updated description.</p>
     */
    _FinalStage description(Optional<String> description);

    _FinalStage description(String description);

    /**
     * <p>Updated badge. Set to null to remove.</p>
     */
    _FinalStage badge(Optional<UpdatePointsSystemRequestItemBadge> badge);

    _FinalStage badge(UpdatePointsSystemRequestItemBadge badge);

    /**
     * <p>Updated max points. Set to null to remove.</p>
     */
    _FinalStage maxPoints(Optional<Integer> maxPoints);

    _FinalStage maxPoints(Integer maxPoints);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements IdStage, _FinalStage {
    private String id;

    private Optional<Integer> maxPoints = Optional.empty();

    private Optional<UpdatePointsSystemRequestItemBadge> badge = Optional.empty();

    private Optional<String> description = Optional.empty();

    private Optional<String> name = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(UpdatePointsSystemRequestItem other) {
      id(other.getId());
      name(other.getName());
      description(other.getDescription());
      badge(other.getBadge());
      maxPoints(other.getMaxPoints());
      return this;
    }

    /**
     * <p>The UUID of the points system to update.</p>
     * <p>The UUID of the points system to update.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("id")
    public _FinalStage id(@NotNull String id) {
      this.id = Objects.requireNonNull(id, "id must not be null");
      return this;
    }

    /**
     * <p>Updated max points. Set to null to remove.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage maxPoints(Integer maxPoints) {
      this.maxPoints = Optional.ofNullable(maxPoints);
      return this;
    }

    /**
     * <p>Updated max points. Set to null to remove.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "maxPoints",
        nulls = Nulls.SKIP
    )
    public _FinalStage maxPoints(Optional<Integer> maxPoints) {
      this.maxPoints = maxPoints;
      return this;
    }

    /**
     * <p>Updated badge. Set to null to remove.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage badge(UpdatePointsSystemRequestItemBadge badge) {
      this.badge = Optional.ofNullable(badge);
      return this;
    }

    /**
     * <p>Updated badge. Set to null to remove.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "badge",
        nulls = Nulls.SKIP
    )
    public _FinalStage badge(Optional<UpdatePointsSystemRequestItemBadge> badge) {
      this.badge = badge;
      return this;
    }

    /**
     * <p>Updated description.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage description(String description) {
      this.description = Optional.ofNullable(description);
      return this;
    }

    /**
     * <p>Updated description.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "description",
        nulls = Nulls.SKIP
    )
    public _FinalStage description(Optional<String> description) {
      this.description = description;
      return this;
    }

    /**
     * <p>Updated name.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage name(String name) {
      this.name = Optional.ofNullable(name);
      return this;
    }

    /**
     * <p>Updated name.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "name",
        nulls = Nulls.SKIP
    )
    public _FinalStage name(Optional<String> name) {
      this.name = name;
      return this;
    }

    @java.lang.Override
    public UpdatePointsSystemRequestItem build() {
      return new UpdatePointsSystemRequestItem(id, name, description, badge, maxPoints, additionalProperties);
    }
  }
}
