package so.trophy.types;

/**
 * This file was auto-generated by Fern from our API Definition.
 */


import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import so.trophy.core.ObjectMappers;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = UpdatedUser.Builder.class
)
public final class UpdatedUser implements IUpdatedUser {
  private final Optional<String> email;

  private final Optional<String> name;

  private final Optional<String> tz;

  private final Optional<List<String>> deviceTokens;

  private final Optional<Boolean> subscribeToEmails;

  private final Optional<Map<String, String>> attributes;

  private final Map<String, Object> additionalProperties;

  private UpdatedUser(Optional<String> email, Optional<String> name, Optional<String> tz,
      Optional<List<String>> deviceTokens, Optional<Boolean> subscribeToEmails,
      Optional<Map<String, String>> attributes, Map<String, Object> additionalProperties) {
    this.email = email;
    this.name = name;
    this.tz = tz;
    this.deviceTokens = deviceTokens;
    this.subscribeToEmails = subscribeToEmails;
    this.attributes = attributes;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The user's email address. Required if subscribeToEmails is true.
   */
  @JsonProperty("email")
  @java.lang.Override
  public Optional<String> getEmail() {
    return email;
  }

  /**
   * @return The name to refer to the user by in emails.
   */
  @JsonProperty("name")
  @java.lang.Override
  public Optional<String> getName() {
    return name;
  }

  /**
   * @return The user's timezone (used for email scheduling).
   */
  @JsonProperty("tz")
  @java.lang.Override
  public Optional<String> getTz() {
    return tz;
  }

  /**
   * @return The user's device tokens, used for push notifications.
   */
  @JsonProperty("deviceTokens")
  @java.lang.Override
  public Optional<List<String>> getDeviceTokens() {
    return deviceTokens;
  }

  /**
   * @return Whether the user should receive Trophy-powered emails. If false, Trophy will not store the user's email address.
   */
  @JsonProperty("subscribeToEmails")
  @java.lang.Override
  public Optional<Boolean> getSubscribeToEmails() {
    return subscribeToEmails;
  }

  /**
   * @return User attributes as key-value pairs. Keys must match existing user attributes set up in the Trophy dashboard.
   */
  @JsonProperty("attributes")
  @java.lang.Override
  public Optional<Map<String, String>> getAttributes() {
    return attributes;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof UpdatedUser && equalTo((UpdatedUser) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(UpdatedUser other) {
    return email.equals(other.email) && name.equals(other.name) && tz.equals(other.tz) && deviceTokens.equals(other.deviceTokens) && subscribeToEmails.equals(other.subscribeToEmails) && attributes.equals(other.attributes);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.email, this.name, this.tz, this.deviceTokens, this.subscribeToEmails, this.attributes);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> email = Optional.empty();

    private Optional<String> name = Optional.empty();

    private Optional<String> tz = Optional.empty();

    private Optional<List<String>> deviceTokens = Optional.empty();

    private Optional<Boolean> subscribeToEmails = Optional.empty();

    private Optional<Map<String, String>> attributes = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(UpdatedUser other) {
      email(other.getEmail());
      name(other.getName());
      tz(other.getTz());
      deviceTokens(other.getDeviceTokens());
      subscribeToEmails(other.getSubscribeToEmails());
      attributes(other.getAttributes());
      return this;
    }

    @JsonSetter(
        value = "email",
        nulls = Nulls.SKIP
    )
    public Builder email(Optional<String> email) {
      this.email = email;
      return this;
    }

    public Builder email(String email) {
      this.email = Optional.ofNullable(email);
      return this;
    }

    @JsonSetter(
        value = "name",
        nulls = Nulls.SKIP
    )
    public Builder name(Optional<String> name) {
      this.name = name;
      return this;
    }

    public Builder name(String name) {
      this.name = Optional.ofNullable(name);
      return this;
    }

    @JsonSetter(
        value = "tz",
        nulls = Nulls.SKIP
    )
    public Builder tz(Optional<String> tz) {
      this.tz = tz;
      return this;
    }

    public Builder tz(String tz) {
      this.tz = Optional.ofNullable(tz);
      return this;
    }

    @JsonSetter(
        value = "deviceTokens",
        nulls = Nulls.SKIP
    )
    public Builder deviceTokens(Optional<List<String>> deviceTokens) {
      this.deviceTokens = deviceTokens;
      return this;
    }

    public Builder deviceTokens(List<String> deviceTokens) {
      this.deviceTokens = Optional.ofNullable(deviceTokens);
      return this;
    }

    @JsonSetter(
        value = "subscribeToEmails",
        nulls = Nulls.SKIP
    )
    public Builder subscribeToEmails(Optional<Boolean> subscribeToEmails) {
      this.subscribeToEmails = subscribeToEmails;
      return this;
    }

    public Builder subscribeToEmails(Boolean subscribeToEmails) {
      this.subscribeToEmails = Optional.ofNullable(subscribeToEmails);
      return this;
    }

    @JsonSetter(
        value = "attributes",
        nulls = Nulls.SKIP
    )
    public Builder attributes(Optional<Map<String, String>> attributes) {
      this.attributes = attributes;
      return this;
    }

    public Builder attributes(Map<String, String> attributes) {
      this.attributes = Optional.ofNullable(attributes);
      return this;
    }

    public UpdatedUser build() {
      return new UpdatedUser(email, name, tz, deviceTokens, subscribeToEmails, attributes, additionalProperties);
    }
  }
}
