package so.trophy.types;

/**
 * This file was auto-generated by Fern from our API Definition.
 */


import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import so.trophy.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = WebhooksPointsChangedPayload.Builder.class
)
public final class WebhooksPointsChangedPayload {
  private final User user;

  private final GetUserPointsResponse points;

  private final Map<String, Object> additionalProperties;

  private WebhooksPointsChangedPayload(User user, GetUserPointsResponse points,
      Map<String, Object> additionalProperties) {
    this.user = user;
    this.points = points;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The webhook event type.
   */
  @JsonProperty("type")
  public String getType() {
    return "points.changed";
  }

  /**
   * @return The user whose points increased or decreased.
   */
  @JsonProperty("user")
  public User getUser() {
    return user;
  }

  /**
   * @return The user's points after the event.
   */
  @JsonProperty("points")
  public GetUserPointsResponse getPoints() {
    return points;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof WebhooksPointsChangedPayload && equalTo((WebhooksPointsChangedPayload) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(WebhooksPointsChangedPayload other) {
    return user.equals(other.user) && points.equals(other.points);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.user, this.points);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static UserStage builder() {
    return new Builder();
  }

  public interface UserStage {
    /**
     * <p>The user whose points increased or decreased.</p>
     */
    PointsStage user(@NotNull User user);

    Builder from(WebhooksPointsChangedPayload other);
  }

  public interface PointsStage {
    /**
     * <p>The user's points after the event.</p>
     */
    _FinalStage points(@NotNull GetUserPointsResponse points);
  }

  public interface _FinalStage {
    WebhooksPointsChangedPayload build();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements UserStage, PointsStage, _FinalStage {
    private User user;

    private GetUserPointsResponse points;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(WebhooksPointsChangedPayload other) {
      user(other.getUser());
      points(other.getPoints());
      return this;
    }

    /**
     * <p>The user whose points increased or decreased.</p>
     * <p>The user whose points increased or decreased.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("user")
    public PointsStage user(@NotNull User user) {
      this.user = Objects.requireNonNull(user, "user must not be null");
      return this;
    }

    /**
     * <p>The user's points after the event.</p>
     * <p>The user's points after the event.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("points")
    public _FinalStage points(@NotNull GetUserPointsResponse points) {
      this.points = Objects.requireNonNull(points, "points must not be null");
      return this;
    }

    @java.lang.Override
    public WebhooksPointsChangedPayload build() {
      return new WebhooksPointsChangedPayload(user, points, additionalProperties);
    }
  }
}
