package so.trophy.types;

/**
 * This file was auto-generated by Fern from our API Definition.
 */


import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import so.trophy.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = WrappedMostActiveMonth.Builder.class
)
public final class WrappedMostActiveMonth implements IWrappedActivityPeriod {
  private final Map<String, WrappedMetric> metrics;

  private final Map<String, WrappedPoints> points;

  private final List<CompletedAchievementResponse> achievements;

  private final Map<String, UserLeaderboardResponse> leaderboards;

  private final int month;

  private final Map<String, Object> additionalProperties;

  private WrappedMostActiveMonth(Map<String, WrappedMetric> metrics,
      Map<String, WrappedPoints> points, List<CompletedAchievementResponse> achievements,
      Map<String, UserLeaderboardResponse> leaderboards, int month,
      Map<String, Object> additionalProperties) {
    this.metrics = metrics;
    this.points = points;
    this.achievements = achievements;
    this.leaderboards = leaderboards;
    this.month = month;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The user's metrics during this period, keyed by metric key.
   */
  @JsonProperty("metrics")
  @java.lang.Override
  public Map<String, WrappedMetric> getMetrics() {
    return metrics;
  }

  /**
   * @return The user's points during this period, keyed by points system key.
   */
  @JsonProperty("points")
  @java.lang.Override
  public Map<String, WrappedPoints> getPoints() {
    return points;
  }

  /**
   * @return Achievements completed during this period.
   */
  @JsonProperty("achievements")
  @java.lang.Override
  public List<CompletedAchievementResponse> getAchievements() {
    return achievements;
  }

  /**
   * @return The user's best leaderboard rankings during this period, keyed by leaderboard key.
   */
  @JsonProperty("leaderboards")
  @java.lang.Override
  public Map<String, UserLeaderboardResponse> getLeaderboards() {
    return leaderboards;
  }

  /**
   * @return The month number (0-11, where 0 is January).
   */
  @JsonProperty("month")
  public int getMonth() {
    return month;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof WrappedMostActiveMonth && equalTo((WrappedMostActiveMonth) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(WrappedMostActiveMonth other) {
    return metrics.equals(other.metrics) && points.equals(other.points) && achievements.equals(other.achievements) && leaderboards.equals(other.leaderboards) && month == other.month;
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.metrics, this.points, this.achievements, this.leaderboards, this.month);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static MonthStage builder() {
    return new Builder();
  }

  public interface MonthStage {
    /**
     * <p>The month number (0-11, where 0 is January).</p>
     */
    _FinalStage month(int month);

    Builder from(WrappedMostActiveMonth other);
  }

  public interface _FinalStage {
    WrappedMostActiveMonth build();

    /**
     * <p>The user's metrics during this period, keyed by metric key.</p>
     */
    _FinalStage metrics(Map<String, WrappedMetric> metrics);

    _FinalStage putAllMetrics(Map<String, WrappedMetric> metrics);

    _FinalStage metrics(String key, WrappedMetric value);

    /**
     * <p>The user's points during this period, keyed by points system key.</p>
     */
    _FinalStage points(Map<String, WrappedPoints> points);

    _FinalStage putAllPoints(Map<String, WrappedPoints> points);

    _FinalStage points(String key, WrappedPoints value);

    /**
     * <p>Achievements completed during this period.</p>
     */
    _FinalStage achievements(List<CompletedAchievementResponse> achievements);

    _FinalStage addAchievements(CompletedAchievementResponse achievements);

    _FinalStage addAllAchievements(List<CompletedAchievementResponse> achievements);

    /**
     * <p>The user's best leaderboard rankings during this period, keyed by leaderboard key.</p>
     */
    _FinalStage leaderboards(Map<String, UserLeaderboardResponse> leaderboards);

    _FinalStage putAllLeaderboards(Map<String, UserLeaderboardResponse> leaderboards);

    _FinalStage leaderboards(String key, UserLeaderboardResponse value);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements MonthStage, _FinalStage {
    private int month;

    private Map<String, UserLeaderboardResponse> leaderboards = new LinkedHashMap<>();

    private List<CompletedAchievementResponse> achievements = new ArrayList<>();

    private Map<String, WrappedPoints> points = new LinkedHashMap<>();

    private Map<String, WrappedMetric> metrics = new LinkedHashMap<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(WrappedMostActiveMonth other) {
      metrics(other.getMetrics());
      points(other.getPoints());
      achievements(other.getAchievements());
      leaderboards(other.getLeaderboards());
      month(other.getMonth());
      return this;
    }

    /**
     * <p>The month number (0-11, where 0 is January).</p>
     * <p>The month number (0-11, where 0 is January).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("month")
    public _FinalStage month(int month) {
      this.month = month;
      return this;
    }

    /**
     * <p>The user's best leaderboard rankings during this period, keyed by leaderboard key.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage leaderboards(String key, UserLeaderboardResponse value) {
      this.leaderboards.put(key, value);
      return this;
    }

    /**
     * <p>The user's best leaderboard rankings during this period, keyed by leaderboard key.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage putAllLeaderboards(Map<String, UserLeaderboardResponse> leaderboards) {
      if (leaderboards != null) {
        this.leaderboards.putAll(leaderboards);
      }
      return this;
    }

    /**
     * <p>The user's best leaderboard rankings during this period, keyed by leaderboard key.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "leaderboards",
        nulls = Nulls.SKIP
    )
    public _FinalStage leaderboards(Map<String, UserLeaderboardResponse> leaderboards) {
      this.leaderboards.clear();
      this.leaderboards.putAll(leaderboards);
      return this;
    }

    /**
     * <p>Achievements completed during this period.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addAllAchievements(List<CompletedAchievementResponse> achievements) {
      if (achievements != null) {
        this.achievements.addAll(achievements);
      }
      return this;
    }

    /**
     * <p>Achievements completed during this period.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addAchievements(CompletedAchievementResponse achievements) {
      this.achievements.add(achievements);
      return this;
    }

    /**
     * <p>Achievements completed during this period.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "achievements",
        nulls = Nulls.SKIP
    )
    public _FinalStage achievements(List<CompletedAchievementResponse> achievements) {
      this.achievements.clear();
      this.achievements.addAll(achievements);
      return this;
    }

    /**
     * <p>The user's points during this period, keyed by points system key.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage points(String key, WrappedPoints value) {
      this.points.put(key, value);
      return this;
    }

    /**
     * <p>The user's points during this period, keyed by points system key.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage putAllPoints(Map<String, WrappedPoints> points) {
      if (points != null) {
        this.points.putAll(points);
      }
      return this;
    }

    /**
     * <p>The user's points during this period, keyed by points system key.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "points",
        nulls = Nulls.SKIP
    )
    public _FinalStage points(Map<String, WrappedPoints> points) {
      this.points.clear();
      this.points.putAll(points);
      return this;
    }

    /**
     * <p>The user's metrics during this period, keyed by metric key.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage metrics(String key, WrappedMetric value) {
      this.metrics.put(key, value);
      return this;
    }

    /**
     * <p>The user's metrics during this period, keyed by metric key.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage putAllMetrics(Map<String, WrappedMetric> metrics) {
      if (metrics != null) {
        this.metrics.putAll(metrics);
      }
      return this;
    }

    /**
     * <p>The user's metrics during this period, keyed by metric key.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "metrics",
        nulls = Nulls.SKIP
    )
    public _FinalStage metrics(Map<String, WrappedMetric> metrics) {
      this.metrics.clear();
      this.metrics.putAll(metrics);
      return this;
    }

    @java.lang.Override
    public WrappedMostActiveMonth build() {
      return new WrappedMostActiveMonth(metrics, points, achievements, leaderboards, month, additionalProperties);
    }
  }
}
